### ISSUE TITLE
UTM tracking 2/5: capture middleware + visit logging

### ISSUE THREAD

**Issue by alexeygrigorev** [AI-Shipping-Labs/website#193]
# UTM tracking 2/5: capture middleware + visit logging

Status: pending
Tags: `seo`, `infra`
Depends on: #192 (Campaign + CampaignLink models — visits resolve FK by `utm_campaign` slug)
Blocks: #194 (signup attribution reads first-touch cookie + last-touch session), #195, #196

## Scope

Add a Django middleware that, on any incoming request bearing one or more `utm_*` query params, persists the UTM tuple as first-touch (long-lived cookie) and last-touch (session), writes a `CampaignVisit` row, and assigns a stable `anonymous_id` cookie so we can later join the visit to a signup (issue #194).

### New app: `analytics`

Create a new Django app `analytics/` (registered in `INSTALLED_APPS`). Holds the model, the middleware, the constants, and the tests. Keeps UTM concerns isolated from `integrations/` (which is for 3rd-party APIs) and from `email_app` (which already owns `EmailCampaign`, an unrelated model).

Note: issue #192 introduces a `Campaign` model. Place it in this same `analytics` app (i.e. `analytics.models.Campaign`, `analytics.models.CampaignLink`) so #193 can `FK` to it cleanly. Issue #192 is being groomed in parallel — coordinate the app name with that grooming.

### Model: `analytics.CampaignVisit`

| Field | Type | Notes |
|---|---|---|
| `id` | BigAutoField | PK |
| `campaign` | FK -> `analytics.Campaign` | `null=True, blank=True, on_delete=SET_NULL`, `related_name='visits'`. Resolved by matching `utm_campaign` to `Campaign.slug` at write time. Null when no matching campaign exists (link minted outside Studio, typo, or `Campaign` not yet created). |
| `utm_source` | CharField(max_length=100) | Trimmed, lowercased, indexed. Empty string if absent. |
| `utm_medium` | CharField(max_length=100) | Same. |
| `utm_campaign` | CharField(max_length=200) | Same. Indexed. |
| `utm_content` | CharField(max_length=200) | Same. |
| `utm_term` | CharField(max_length=200) | Same. |
| `path` | CharField(max_length=500) | Landing path (`request.path`, no querystring). |
| `referrer` | CharField(max_length=500, blank=True) | `HTTP_REFERER` header, truncated to 500. |
| `user_agent` | CharField(max_length=500, blank=True) | Truncated to 500. |
| `ip_hash` | CharField(max_length=64, blank=True) | SHA-256 of `client_ip + IP_HASH_SALT`. Raw IP is NOT stored (GDPR — see "Privacy" below). |
| `anonymous_id` | CharField(max_length=36) | UUID4 from the `aslab_aid` cookie. Indexed. |
| `user` | FK -> `AUTH_USER_MODEL` | `null=True, blank=True, on_delete=SET_NULL`, `related_name='campaign_visits'`. Set when `request.user.is_authenticated` at request time. |
| `ts` | DateTimeField | `auto_now_add=True`. Indexed (descending). |

Indexes:
- `Index(fields=['campaign', '-ts'])` — used by issue #196 dashboard
- `Index(fields=['anonymous_id', '-ts'])` — used by issue #194 to backfill `user` on signup
- `Index(fields=['utm_campaign', '-ts'])` — used when no matching `Campaign` row exists

### Middleware: `analytics.middleware.CampaignTrackingMiddleware`

Register in `settings.MIDDLEWARE` AFTER `SessionMiddleware` and AFTER `AuthenticationMiddleware` (it reads `request.session` and `request.user`), and BEFORE `RedirectMiddleware`.

Constants (defined as module-level or pulled from `settings`):

```
UTM_PARAMS = ('utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term')

FIRST_TOUCH_COOKIE = 'aslab_ft'         # JSON: {source, medium, campaign, content, term, ts}
ANON_ID_COOKIE     = 'aslab_aid'        # UUID4 string
SESSION_LAST_TOUCH = 'aslab_lt'         # dict, same shape as cookie

COOKIE_MAX_AGE     = 60 * 60 * 24 * 90  # 90 days
COOKIE_SAMESITE    = 'Lax'              # allows top-level cross-site nav (newsletter clicks)
COOKIE_SECURE      = not settings.DEBUG
COOKIE_HTTPONLY    = True
COOKIE_DOMAIN      = settings.SESSION_COOKIE_DOMAIN  # reuse Django's setting; defaults to None
```

Algorithm (run on every request, in `__call__`):

1. Skip-fast checks — if any is true, call `get_response(request)` without writing anything:
   - `request.method` not in `('GET', 'HEAD')`
   - `request.path` starts with any of: `/admin/`, `/static/`, `/media/`, `/api/webhooks/`, `/healthz`, `/favicon.ico`, `/sitemap.xml`, `/robots.txt`
   - User-Agent matches the bot regex (see "Bot filter")
2. Ensure `anonymous_id` — read `aslab_aid` from cookies; if missing or not a valid UUID, generate `uuid.uuid4()` and remember to set the cookie on the response.
3. Extract UTMs — read `utm_*` from `request.GET`. Lowercase, strip whitespace, truncate to model max_length. If ALL five are empty, skip steps 4-7 (just ensure the anon cookie is set, then return).
4. First-touch — if `aslab_ft` cookie is absent, mark to set it on the response with the current UTM dict + ISO timestamp. If present, leave alone (first-touch is sticky for 90 days).
5. Last-touch — overwrite `request.session['aslab_lt']` with the current UTM dict + ISO timestamp. Always.
6. Write `CampaignVisit` — resolve `Campaign` by `utm_campaign` slug (cached lookup, see "Performance"); build kwargs; enqueue with `jobs.tasks.async_task('analytics.tasks.record_visit', **kwargs)` so the request isn't blocked by a DB write. Fall back to a synchronous `CampaignVisit.objects.create(...)` if `Q_CLUSTER['sync'] = True` (test mode).
7. Get the response, set cookies, return.

Cookie write rules (on the outgoing response):
- `aslab_aid` — set if it was newly generated; `max_age=COOKIE_MAX_AGE`, `samesite=Lax`, `httponly=True`, `secure=COOKIE_SECURE`, `domain=COOKIE_DOMAIN`.
- `aslab_ft` — set only if step 4 marked it; same flags as above; value is `json.dumps(...)`.

Authenticated-user behavior:
- A logged-in user hitting a `utm_*` URL still gets a `CampaignVisit` row written WITH `user_id` set. We don't suppress logging for known users — re-engagement campaigns (e.g. existing free user clicks an upgrade campaign) are valuable signal.
- The first-touch cookie is NOT updated for them either way (it remains whatever it was); last-touch session IS updated.

### Bot filter

Drop visits whose `User-Agent` matches a case-insensitive regex of common bots. Define as a single compiled regex in `analytics/bots.py`:

```
BOT_UA_RE = re.compile(
    r'(bot|crawler|spider|slurp|bingpreview|facebookexternalhit|'
    r'twitterbot|linkedinbot|slackbot|discordbot|telegrambot|'
    r'whatsapp|preview|monitor|uptime|pingdom|googleother|'
    r'headlesschrome|phantomjs|puppeteer|playwright|cypress|httpclient|'
    r'curl|wget|python-requests|node-fetch|go-http-client)',
    re.IGNORECASE,
)
```

A bot hit is a no-op for the middleware (no anon cookie, no first-touch, no session, no row). Document that this is heuristic, not airtight.

Note: `playwright` is in the regex on purpose. Tests that need to exercise the middleware must override the user-agent (see "Test scenarios" — uses Django `Client` with explicit `HTTP_USER_AGENT`).

### Privacy / GDPR — IP handling

We do NOT store raw IP addresses. We store `ip_hash = sha256(ip + IP_HASH_SALT)` where `IP_HASH_SALT` is a Django setting read from env (`IP_HASH_SALT`, default `''`). Rationale:
- We only need IP to deduplicate "unique visitors" per campaign (issue #196). A salted hash gives us that without retaining PII.
- If `IP_HASH_SALT` is the empty string, `ip_hash` is left blank (no PII leak from misconfiguration). Document this in the settings comment.
- Client IP is sourced from `HTTP_X_FORWARDED_FOR` (first hop) if present, else `REMOTE_ADDR`.

Cookies (`aslab_aid`, `aslab_ft`) are first-party, functional analytics. Document in the privacy notice (out of scope for this issue but flagged for the next docs pass).

### Performance

- `Campaign` lookup by slug is cached for 5 minutes via `django.core.cache` keyed by `f'analytics:campaign:{slug}'`. Cache misses are also cached as `None` for 60s to avoid repeated lookups for unknown slugs.
- The `CampaignVisit.objects.create(...)` happens via `jobs.tasks.async_task('analytics.tasks.record_visit', ...)`, so the request response is not blocked by a write. In tests, `Q_CLUSTER['sync'] = True` (already configurable via env `Q_SYNC=true`) makes the task run inline.
- Bot filter and skip-path filter run BEFORE any DB or cache call so 99% of bot traffic is one regex match.

### Settings additions

```python
# website/settings.py
IP_HASH_SALT = os.environ.get('IP_HASH_SALT', '')
ANALYTICS_COOKIE_DOMAIN = os.environ.get('ANALYTICS_COOKIE_DOMAIN', '') or None
```

### File layout

```
analytics/
  __init__.py
  apps.py
  middleware.py        # CampaignTrackingMiddleware
  bots.py              # BOT_UA_RE
  models/
    __init__.py
    visit.py           # CampaignVisit
    # campaign.py and campaign_link.py land via issue #192
  tasks.py             # record_visit(**kwargs)
  admin.py             # readonly admin for CampaignVisit
  migrations/
    0001_initial.py    # CampaignVisit + indexes (depends on issue 192's migration if shipped first)
  tests/
    __init__.py
    test_middleware.py
    test_visit_model.py
    test_tasks.py
```

## Acceptance Criteria

- [x] `analytics` app created and added to `INSTALLED_APPS`
- [x] `CampaignTrackingMiddleware` registered in `MIDDLEWARE` after `SessionMiddleware` and `AuthenticationMiddleware`, before `RedirectMiddleware`
- [x] `CampaignVisit` model exists with all fields and indexes listed in Scope
- [x] Visit to `/blog?utm_source=newsletter&utm_medium=email&utm_campaign=launch&utm_content=hero` creates exactly one `CampaignVisit` row with all five UTM fields populated
- [x] Visit to a path with NO `utm_*` params creates ZERO `CampaignVisit` rows (but still sets the `aslab_aid` cookie if missing)
- [x] Two consecutive UTM-bearing requests in the same browser create TWO `CampaignVisit` rows but the `aslab_ft` cookie is set only on the first response (first-touch is sticky)
- [x] Two consecutive UTM-bearing requests in the same browser end with `request.session['aslab_lt']` equal to the SECOND request's UTM tuple (last-touch is overwritten every time)
- [x] `aslab_aid` cookie is set as a UUID4, `httponly=True`, `samesite=Lax`, `max_age=7776000` (90d)
- [x] `aslab_ft` cookie persists the first UTM tuple as JSON with the same cookie flags
- [x] When `utm_campaign=launch` matches an existing `Campaign(slug='launch')`, the resulting `CampaignVisit.campaign_id` is set to that campaign's PK
- [x] When `utm_campaign=does_not_exist` has no matching `Campaign`, the resulting `CampaignVisit.campaign` is `NULL` and `utm_campaign` field stores the literal string
- [x] An authenticated user visiting a UTM URL produces a `CampaignVisit` with `user_id` set to that user
- [x] Requests with bot User-Agents (`Googlebot/2.1`, `python-requests/2.31`, `curl/8.0`) produce ZERO `CampaignVisit` rows even when UTMs are present
- [x] Requests to `/admin/...`, `/static/...`, `/api/webhooks/...`, `/sitemap.xml`, `/robots.txt`, `/favicon.ico` produce ZERO `CampaignVisit` rows even when UTMs are present
- [x] POST requests produce ZERO `CampaignVisit` rows
- [x] When `IP_HASH_SALT` is set, `ip_hash` is a 64-char hex string; when unset, `ip_hash` is empty
- [x] Raw IP address is NOT stored in any column of `CampaignVisit`
- [x] `utm_source`, `utm_medium`, `utm_campaign`, `utm_content`, `utm_term` are normalized to lowercase + stripped of leading/trailing whitespace before being persisted
- [x] UTM values longer than the column max_length are truncated, not rejected
- [x] `Campaign` slug -> id lookup is cached (verify by checking that two consecutive UTM hits with the same `utm_campaign` produce only one Campaign DB query)
- [x] `record_visit` task runs via `jobs.tasks.async_task` in production code paths; in tests it runs synchronously via `Q_SYNC=true`
- [x] Migration `analytics/migrations/0001_initial.py` is included
- [x] Django admin registration for `CampaignVisit` (read-only, list_display = source/medium/campaign/path/ts/user)
- [x] All existing tests still pass (no regressions in `integrations/tests/test_middleware.py`, accounts, payments, etc.)
- [ ] [HUMAN] Verify on staging: visit a UTM URL in a real browser, then check that `aslab_aid` and `aslab_ft` cookies appear in DevTools with the documented domain/SameSite/Secure flags

## Django Test Scenarios

Middleware behavior cannot be meaningfully Playwright-tested (it has no UI surface), so the tests live as `django.test.TestCase` cases in `analytics/tests/test_middleware.py` using `Client(HTTP_USER_AGENT='Mozilla/5.0 (test browser)')` to bypass the bot filter. Each scenario is a real attribution story.

### Scenario: First-time visitor from a tagged newsletter link is captured as first-touch
Given: A clean browser (no cookies, no session) and a `Campaign(slug='launch_april2026')` exists
1. GET `/blog?utm_source=newsletter&utm_medium=email&utm_campaign=launch_april2026&utm_content=hero` with a real-browser User-Agent
Then: Exactly one `CampaignVisit` row exists, with all five UTM fields populated and `campaign` linked to the `launch_april2026` Campaign
Then: Response sets the `aslab_aid` cookie (UUID4) and the `aslab_ft` cookie (JSON containing the UTM tuple)
Then: Response status is 200 (not redirected, not blocked)

### Scenario: Returning visitor on a second campaign keeps first-touch but updates last-touch
Given: A browser that already has `aslab_aid` and `aslab_ft={source:newsletter,...,campaign:launch_april2026}` cookies set
1. GET `/courses?utm_source=twitter&utm_medium=social&utm_campaign=summer_drop&utm_content=cta_a`
Then: A new `CampaignVisit` row is created with `utm_source=twitter`, `utm_campaign=summer_drop`
Then: The `aslab_ft` cookie is NOT modified by the response (first-touch is sticky)
Then: `request.session['aslab_lt']` equals the summer_drop UTM tuple (last-touch overwritten)

### Scenario: Visitor browsing without UTMs is silently tracked for identity but no visit row is logged
Given: A clean browser
1. GET `/blog` (no `utm_*` params)
Then: Response sets the `aslab_aid` cookie
Then: ZERO `CampaignVisit` rows are created
Then: `aslab_ft` cookie is NOT set (we only have first-touch when UTMs are present)

### Scenario: Authenticated member clicking a re-engagement campaign link is attributed to their user account
Given: A user `main@test.com` is logged in; a `Campaign(slug='reactivation')` exists
1. GET `/pricing?utm_source=email&utm_medium=email&utm_campaign=reactivation&utm_content=upgrade_cta`
Then: A `CampaignVisit` row is created with `user_id=main@test.com.id`, `anonymous_id` set, and `campaign` linked to `reactivation`

### Scenario: Bot crawl does not pollute campaign analytics
Given: A clean state and a `Campaign(slug='launch_april2026')`
1. GET `/blog?utm_source=newsletter&utm_campaign=launch_april2026` with `User-Agent: Googlebot/2.1`
2. GET same URL with `User-Agent: python-requests/2.31.0`
3. GET same URL with `User-Agent: curl/8.0.1`
Then: ZERO `CampaignVisit` rows exist
Then: No `aslab_aid` or `aslab_ft` cookies are set on the responses

### Scenario: System endpoints are excluded from tracking
Given: A clean state
1. GET `/admin/login/?utm_source=spam&utm_campaign=test`
2. GET `/static/css/main.css?utm_source=spam&utm_campaign=test`
3. POST `/api/webhooks/payments?utm_source=spam&utm_campaign=test`
4. GET `/sitemap.xml?utm_source=spam&utm_campaign=test`
Then: ZERO `CampaignVisit` rows exist (admin, static, webhooks, sitemap are all skipped)

### Scenario: Unknown campaign slug still logs the visit for later reconciliation
Given: A clean state; NO `Campaign` row exists with slug `mystery_link`
1. GET `/blog?utm_source=somewhere&utm_medium=link&utm_campaign=mystery_link&utm_content=v1`
Then: A `CampaignVisit` row exists with `utm_campaign='mystery_link'` and `campaign IS NULL`
Then: After-the-fact, creating `Campaign(slug='mystery_link')` does NOT retroactively backfill the row (FK is set at write time only — confirm this is the documented behavior)

### Scenario: UTM values are normalized so analytics group correctly
Given: A clean state and a `Campaign(slug='launch')`
1. GET `/blog?utm_source=Newsletter&utm_medium=EMAIL&utm_campaign=Launch%20%20&utm_content=Hero%20Image`
Then: The persisted `CampaignVisit` has `utm_source='newsletter'`, `utm_medium='email'`, `utm_campaign='launch'`, `utm_content='hero image'` (lowercased + trimmed)
Then: `campaign` FK resolves to the existing `launch` campaign despite the original casing in the URL

### Scenario: Privacy — raw IP is never stored
Given: `IP_HASH_SALT='test_salt'`
1. GET `/blog?utm_source=newsletter&utm_campaign=launch` with `REMOTE_ADDR='203.0.113.42'`
Then: The resulting `CampaignVisit.ip_hash` is the SHA-256 of `'203.0.113.42' + 'test_salt'` (64 hex chars)
Then: No column on the row contains the literal string `'203.0.113.42'`

### Scenario: Performance — repeated UTM hits do not re-query the Campaign table
Given: A `Campaign(slug='launch')` and a clean cache
1. With `assertNumQueries`, hit `/blog?utm_campaign=launch` three times in a row
Then: The Campaign lookup hits the DB once across the three requests (cached for the next two), confirming the slug cache works

### Scenario: First-touch survives across many sessions but last-touch is per-session
Given: A clean browser; first request sets first-touch + last-touch via `?utm_campaign=newsletter`
1. Simulate session expiry (clear `request.session` between requests but keep cookies)
2. GET `/blog?utm_campaign=blog_link`
Then: The `aslab_ft` cookie still contains `newsletter` (survived the session)
Then: `request.session['aslab_lt']` now contains `blog_link` (re-established for new session)

### Scenario: Anonymous visitor tracked across multiple visits keeps a stable `anonymous_id`
Given: A clean browser
1. GET `/blog?utm_campaign=launch`
2. GET `/courses?utm_campaign=summer_drop`
3. GET `/events?utm_campaign=q3_event`
Then: All three `CampaignVisit` rows share the same `anonymous_id`
Then: This `anonymous_id` is the value of the `aslab_aid` cookie set on the first response (so issue #194 can backfill `user_id` on signup)

---

Blocked by: #192

**Comment by alexeygrigorev** [comment]
## Grooming Complete

### Summary
A `CampaignTrackingMiddleware` that captures `utm_*` query params on every safe-method request, persists first-touch in a 90-day cookie + last-touch in the session, writes a `CampaignVisit` row (FK to `Campaign` resolved by `utm_campaign` slug, nullable), and assigns a stable `anonymous_id` cookie. New `analytics` Django app holds the model, middleware, bot regex, and the async write task.

### Key Decisions
- New `analytics` app — keeps UTM concerns separate from `integrations/` (3rd-party APIs) and from `email_app.EmailCampaign` (unrelated). Issue #192's `Campaign`/`CampaignLink` should land in this same app so #193 can FK directly.
- Cookies: `aslab_aid` (UUID4 anonymous_id, 90d) and `aslab_ft` (JSON UTM tuple, 90d). Both `httponly=True`, `samesite=Lax` (so newsletter top-level navigation carries them), `secure=not DEBUG`. Cookie domain reuses `SESSION_COOKIE_DOMAIN`.
- Last-touch lives in `request.session` (not a separate cookie) — Django sessions already exist, no extra storage decisions needed; expires with the session, which matches "most recent campaign in this browsing window" semantics.
- Authenticated users still get `CampaignVisit` rows written WITH `user_id` — re-engagement campaign signal is valuable. First-touch cookie is never overwritten once set.
- Visit writes go through `jobs.tasks.async_task` (django-q2) so the request is not blocked by a DB write. Tests run inline via the existing `Q_SYNC=true` mode.
- GDPR: raw IP is NEVER stored. We persist `sha256(ip + IP_HASH_SALT)` for unique-visitor counting in #196. If the salt is unset, `ip_hash` is empty (fail-safe, no PII leak).
- Bot filter: single compiled regex covering Googlebot, social previewers, headless browsers, HTTP libraries, and Playwright. Tests must pass an explicit real-browser `HTTP_USER_AGENT` to exercise the middleware.
- Skip-list: `/admin/`, `/static/`, `/media/`, `/api/webhooks/`, `/healthz`, `/sitemap.xml`, `/robots.txt`, `/favicon.ico`, plus all non-GET/HEAD methods.
- Campaign slug -> id lookup is cached for 5 min via `django.core.cache` (negative lookups cached for 60s) to avoid a DB hit on every UTM request.
- FK is set at write time only — if a `Campaign` is created later with a slug that matches existing visits, those visits do NOT get backfilled. Documented as a deliberate decision.
- Middleware order: after `SessionMiddleware` and `AuthenticationMiddleware` (it reads both), before `RedirectMiddleware`.

### Dependencies
- #192 — defines the `Campaign` model that `CampaignVisit.campaign` FKs to. The migration order matters: #192's migration must apply first.

### Tests
- 11 Django `TestCase` scenarios in `analytics/tests/test_middleware.py` covering: first-touch capture, last-touch overwrite, no-UTM no-row, authenticated user attribution, bot filtering, skip-list, unknown campaign slug, value normalization, IP hashing, query caching, anon-id stability across visits.
- No Playwright tests — middleware has no UI surface; `Client(HTTP_USER_AGENT=...)` is the right tool.

### Open Questions
None blocking. Two non-blocking items flagged for future work:
- The privacy notice / cookie banner copy needs an update to mention `aslab_aid` and `aslab_ft`. Out of scope for this issue.
- We could later add an `Index(fields=['user', '-ts'])` on `CampaignVisit` for "show me my own attribution" features — defer until a feature actually needs it.

Ready for implementation.

**Comment by alexeygrigorev** [comment]
## Software Engineer Report

Implementation complete; awaiting tester review before commit/push.

### New `analytics` app

Files created:

- `analytics/__init__.py`
- `analytics/apps.py` — `AnalyticsConfig`
- `analytics/bots.py` — `BOT_UA_RE` + `is_bot()` helper
- `analytics/middleware.py` — `CampaignTrackingMiddleware`
- `analytics/tasks.py` — `record_visit()` + cached `_resolve_campaign_id()`
- `analytics/models/__init__.py`
- `analytics/models/visit.py` — `CampaignVisit` model
- `analytics/admin/__init__.py`
- `analytics/admin/visit.py` — read-only `CampaignVisitAdmin`
- `analytics/migrations/__init__.py`
- `analytics/migrations/0001_initial.py` — depends on `integrations.0014_utmcampaign_utmcampaignlink`
- `analytics/tests/__init__.py`
- `analytics/tests/test_middleware.py` — 25 middleware tests
- `analytics/tests/test_tasks.py` — 7 task / cache tests
- `analytics/tests/test_visit_model.py` — 4 model tests + index/FK behavior

### Files modified

- `website/settings.py` — added `analytics` to `INSTALLED_APPS`, registered `CampaignTrackingMiddleware` in `MIDDLEWARE` (after `AccountMiddleware`, before `RedirectMiddleware`), added `IP_HASH_SALT` and `ANALYTICS_COOKIE_DOMAIN` settings.

### Tests

- `analytics` app: 37 passing
- Full Django suite: 3574 passing (no regressions)
- Run with `uv run python manage.py test analytics` (no env vars needed — tests override `Q_CLUSTER` to sync) or `Q_SYNC=true uv run python manage.py test --parallel`.

### Key design notes

- FK is to `integrations.UtmCampaign` (the model `#192` shipped) — not a new `analytics.Campaign`. The groomed spec referenced both names; I went with the existing one to avoid duplication.
- Middleware reads `Q_CLUSTER['sync']` directly so `record_visit` runs inline in test mode without requiring `Q_SYNC=true` env var. Production still goes through `jobs.tasks.async_task` -> django-q.
- `_resolve_campaign_id` uses `cache.get_or_set`-style caching with positive (5 min) and negative (60 s) TTLs. Negative cache uses a sentinel string because Django's cache treats `None` as "not present".
- Empty user-agent is NOT treated as a bot to avoid dropping legitimate visitors (real bots almost always identify themselves).
- Test `Client` default UA is empty, so tests use a `make_browser_client()` helper that sets `HTTP_USER_AGENT='Mozilla/5.0 (test browser)'`.
- Cookie domain reuses `SESSION_COOKIE_DOMAIN` (or `ANALYTICS_COOKIE_DOMAIN` if set), per spec.

### What works

- Middleware writes one `CampaignVisit` per UTM-bearing GET; resolves FK by slug; falls back to NULL when slug is unknown.
- First-touch cookie (`aslab_ft`) sticky across requests; last-touch (`aslab_lt`) overwritten in session every time.
- `aslab_aid` UUID4 cookie persistent across visits (used by `#194` for signup attribution).
- Bot regex skips Googlebot/curl/python-requests/Playwright etc.
- Skip-list covers `/admin/`, `/static/`, `/media/`, `/api/webhooks/`, `/healthz`, `/favicon.ico`, `/sitemap.xml`, `/robots.txt`, plus all non-GET methods.
- IP only stored as `sha256(ip + IP_HASH_SALT)`; blank when salt unset.
- UTM values lowercased + trimmed + truncated to model max-length.
- Campaign slug -> id lookup cached for 5 min; misses cached for 60s.
- Read-only Django admin registered, with `list_display` of source/medium/campaign/path/ts/user.

### Known limitations

- Test `test_three_hits_only_one_campaign_lookup` asserts on raw SQL (case-insensitive substring on table name). It works but is somewhat brittle if Django ever changes how it formats SELECT statements. Acceptable for now.
- The bot regex is heuristic — sophisticated bots that spoof a real browser UA will leak through.
- `[HUMAN]` AC item left unchecked — needs staging verification of cookie flags in DevTools.

**Comment by alexeygrigorev** [comment]
## QA Review

### Test Summary

| Suite | Result |
|---|---|
| Analytics app (37 tests) | 37 passed / 0 failed |
| Full Django suite | 3574 passed / 0 failed in 88s |
| `integrations.tests` (regression check, since middleware shares request path with `RemoveTrailingSlashMiddleware` / `RedirectMiddleware`) | 342 passed / 0 failed |
| `accounts` + `payments` (regression check, depends on session + auth middleware ordering) | 563 passed / 0 failed |
| Playwright E2E | 283 passed / 79 failed (all 79 failures are pre-existing on `main` HEAD, unrelated to #193 — see below) |

### Acceptance Criteria — all verified

- [x] `analytics` app added to `INSTALLED_APPS`
- [x] Middleware registered after `SessionMiddleware` (line 72) + `AuthenticationMiddleware` (line 75) and before `RedirectMiddleware` (line 80) — verified in `website/settings.py`
- [x] `CampaignVisit` model fields + indexes match spec (FK to `integrations.UtmCampaign` per the actual #192 model name)
- [x] Visit with all 5 utm params creates one row populated with all five
- [x] No-UTM visit creates 0 rows but still sets `aslab_aid` cookie
- [x] Two consecutive UTM visits → 2 rows, but `aslab_ft` set only on first response (sticky); confirmed live via curl: second response Set-Cookie omits `aslab_ft`
- [x] `request.session['aslab_lt']` overwritten on each UTM visit (covered by `FirstTouchStickyTest.test_session_last_touch_overwritten_by_second_request`)
- [x] `aslab_aid` cookie is UUID4, HttpOnly, SameSite=Lax, Max-Age=7776000 — verified via live curl headers
- [x] `aslab_ft` cookie persists UTM tuple as JSON with same flags — verified via live curl
- [x] FK resolves when `utm_campaign` matches an existing `UtmCampaign.slug` — verified live (`fk=1` for `ai_shipping_labs_launch_april2026`)
- [x] FK is NULL when no matching campaign exists — verified live (`summer_drop` → `fk=None`); `utm_campaign` literal still stored
- [x] Authenticated user → `user_id` set (test + spec covered)
- [x] Bot UAs (Googlebot, python-requests, curl) → 0 rows + no cookies set; verified live with `curl -A 'Googlebot/2.1'` returning a 200 with no `aslab_*` Set-Cookie
- [x] Skip-list (`/admin/`, `/static/`, `/api/webhooks/`, `/sitemap.xml`, `/robots.txt`, `/favicon.ico`, `/healthz`, `/media/`) → 0 rows + no cookies; verified live for `/admin/`, `/static/something`, `/sitemap.xml`
- [x] POST → 0 rows; verified live (POST returned 403 from CSRF, but middleware would've skipped anyway since `request.method` check runs first)
- [x] `IP_HASH_SALT='devsalt'` produces a 64-hex `ip_hash`; empty salt → blank `ip_hash` (covered by `IpHashPrivacyTest`); verified live (row had `ip_hash=cb07d129f6d8...`)
- [x] Raw IP not stored in any column (asserted explicitly in `test_ip_is_hashed_never_stored_raw`)
- [x] UTM values lowercased + trimmed + truncated (`NormalizationTest.test_uppercase_and_whitespace_normalized`, `test_long_utm_value_truncated_not_rejected`)
- [x] Slug→id lookup cached (`CampaignSlugCacheTest.test_three_hits_only_one_campaign_lookup`, `ResolveCampaignIdTest.test_caches_hit/miss_so_second_call_does_not_query_db`)
- [x] `record_visit` runs via `jobs.tasks.async_task` in production; `Q_CLUSTER['sync']=True` runs inline in tests (verified by reading `_enqueue_visit` and the test's `SYNC_Q_CLUSTER` override)
- [x] Migration `analytics/migrations/0001_initial.py` present; depends on `integrations.0014_utmcampaign_utmcampaignlink` — exists
- [x] Read-only admin registered (`CampaignVisitAdmin.has_add_permission` returns False; `has_change_permission` returns False on existing object)
- [x] No regressions in existing tests (Django suite: 3574/3574)
- [ ] [HUMAN] DevTools verification on staging — out of scope for QA

### Live sanity check (manual `curl` against `runserver` with `Q_SYNC=true IP_HASH_SALT=devsalt`)

Seeded `UtmCampaign(slug='ai_shipping_labs_launch_april2026')`, then:

1. `GET /?utm_source=newsletter&utm_medium=email&utm_campaign=ai_shipping_labs_launch_april2026&utm_content=ai_hero_list` with browser UA →
   - `Set-Cookie: aslab_aid=<uuid4>` and `Set-Cookie: aslab_ft=<JSON>` both with `HttpOnly; Max-Age=7776000; SameSite=Lax`
   - One `CampaignVisit` row written, `campaign_id=1`, `ip_hash` populated (64 hex)
2. Second visit with `?utm_campaign=summer_drop` (different campaign), same cookie jar →
   - Response Set-Cookie does NOT include `aslab_aid` or `aslab_ft` (sticky as expected)
   - Second `CampaignVisit` row written, same `anonymous_id`, `campaign_id=None` (slug not in `UtmCampaign`)
3. `GET /?utm_*` with `Googlebot/2.1` UA → no row, no `aslab_*` cookies
4. `GET /admin/?utm_*`, `/static/something?utm_*`, `/sitemap.xml?utm_*` → no rows, no `aslab_*` cookies
5. `POST /?utm_*` → no row (CSRF blocks at 403 but middleware also drops before that)

Counts after all sanity calls: 2 rows total (matching expectation: only the two GET-with-UTM-bearing requests).

### Issues found

#### 1. Unrelated diff in `_docs/setup.md` (BLOCKER for commit)

The working tree contains an addition to `_docs/setup.md` that adds a new "GitHub App (content sync)" section about content syncing with GitHub Apps. This has nothing to do with UTM tracking / issue #193 and looks like leakage from a different feature/branch. The SWE summary mentions only `analytics/` and `website/settings.py` — the setup.md change should be reverted before commit (or, if the SWE intentionally added it, moved to a separate PR).

```bash
git diff --stat
 _docs/setup.md      | 30 ++++++++++++++++++++++++++++++
 website/settings.py | 10 ++++++++++
```

Recommend: `git checkout -- _docs/setup.md` before committing.

#### 2. Borderline test (advisory only — not blocking)

`analytics/tests/test_visit_model.py::CampaignVisitModelTest::test_create_with_minimum_fields` is close to a Django ORM round-trip test (`testing-guidelines.md` Rule 3). It does pin the "anonymous_id is the only required field" contract, so it's defensible. Not blocking.

#### 3. Playwright pre-existing breakage (NOT caused by #193)

79 Playwright tests fail with `ImportError: cannot import name 'Recording' from 'content.models'` and `TypeError: Event() got unexpected keyword arguments: 'youtube_url', 'google_embed_url', 'date'`. Both are caused by the recent `02ce799 Unify events and recordings into single model` change — the test fixtures were not updated. I confirmed by stashing the analytics changes and rerunning: identical failures persist. These need a separate ticket; they are NOT a regression introduced by this PR.

### Verdict: PASS (conditional on reverting the unrelated `_docs/setup.md` diff before commit)

All acceptance criteria verified by code review + live HTTP testing + 37 dedicated analytics tests + zero regressions in the broader Django suite. The implementation is correct and well-aligned with the spec, including the cookie attributes (HttpOnly/Lax/Max-Age/secure-when-not-DEBUG/domain), GDPR IP hashing (with empty-salt safety), bot regex, skip-list, sync-mode escape hatch for tests, positive+negative slug caching, and middleware ordering.

The setup.md leakage is the only commit-blocker. Once that file is reverted, this can ship.

**Comment by alexeygrigorev** [comment]
## Product Review (DX)

### Privacy posture
Sound. Raw IP never persisted; `ip_hash` is SHA-256 of `ip + IP_HASH_SALT` and stays empty when salt is unset (fail-safe — no PII leak from misconfiguration). Cookies are first-party functional (`HttpOnly`, `SameSite=Lax`, `Secure` when not `DEBUG`, 90d max-age, scope reuses `SESSION_COOKIE_DOMAIN`). Anonymous-id is a stable UUID4 in `aslab_aid` so #194 can backfill `user_id` on signup.

### Capture behavior
Matches spec end-to-end: first-touch sticky in `aslab_ft` cookie, last-touch overwritten in session every hit, UTM values lowercased + trimmed + truncated, `UtmCampaign` resolved by slug with positive (5m) and negative (1m, sentinel-based) caching, async write via `jobs.async_task` with sync fallback under `Q_SYNC=true`. Skip-fast filters (`/admin/`, `/static/`, `/media/`, `/api/webhooks/`, `/sitemap.xml`, `/robots.txt`, `/favicon.ico`, `/healthz`, non-GET/HEAD, bot UA) run before any DB or cache call.

### Admin
Read-only `CampaignVisitAdmin` with sensible `list_display` / `list_filter` / `search_fields` / `date_hierarchy`. Superuser-only delete for cleaning bot pollution — good safety default.

### Verdict: ACCEPT

Ready to ship. The `[HUMAN]` staging cookie-flag check remains for post-deploy verification, as expected.
