### ISSUE TITLE
Wire up pytest-xdist to actually parallelize local Playwright runs

### ISSUE THREAD

**Issue by alexeygrigorev** [AI-Shipping-Labs/website#1470]
## Problem

`pyproject.toml` declares `pytest-xdist>=3.8.0` with the comment "parallelizes the Playwright test run", but no invocation actually uses it:

- `Makefile`: `test-playwright`, `test-playwright-core`, `test-playwright-manual-visual`, `test-visual-regression` all run plain `uv run pytest ... -v` with no `-n` flag.
- `.github/workflows/ci.yml` line 378: same, plain `pytest ... -v`, no `-n`.
- `deploy-dev.yml` parallelizes via a GitHub Actions matrix (multiple runner machines/shards), which is a different mechanism and out of scope here — this issue is about single-machine `-n` parallelism for local/per-issue runs.

Result: `make test-playwright-core`'s ~906 tests run strictly serially. Measured real runs during a recent backlog-clearing batch: 5621s (93.7 min) and 5573s (92.9 min) for two different clean, uncontended runs of the same 906-test core subset. This is now the dominant cost of per-issue agent verification — full Django suite scoping (#1468) does not touch this number at all, since `test-playwright-core` runs regardless.

## Why it's not a simple flag flip

Investigated `playwright_tests/conftest.py`:

- The Django dev server + port fixture is `@pytest.fixture(scope="session")`, resolved via `_pick_free_port()` (OS-assigned free port) unless `PLAYWRIGHT_DJANGO_PORT` is explicitly set. Each xdist worker runs its own internal pytest session, so each would independently resolve its own free port — this part looks safe already.
- `PlaywrightWorktreeGuard` (`playwright_tests/worktree_guard.py`) explicitly blocks a second concurrent Playwright session in the same worktree, specifically because two sessions would share one SQLite file (`test_playwright_db.sqlite3` per worktree, no per-session/per-worker suffix). xdist workers spawned from one `pytest -n auto` invocation ARE effectively concurrent sessions sharing the same worktree checkout — it is not yet verified whether the guard would incorrectly block xdist's own workers, or whether they'd all pass the guard and then corrupt/contend on the single shared SQLite file.
- No `PYTEST_XDIST_WORKER`-aware DB naming exists anywhere in `website/settings.py` or the Playwright conftest, unlike the existing per-worktree isolation (which keys off the worktree path, not a worker id within one invocation).

## Scope

1. Determine whether `PlaywrightWorktreeGuard` needs to become xdist-worker-aware (distinguish "another agent's separate `make test-playwright` invocation in the same worktree" — which must still be blocked, per existing behavior and issue history — from "my own xdist worker siblings within this single invocation" — which must be allowed to proceed together).
2. Give each xdist worker its own isolated SQLite test DB file (standard pytest-django + pytest-xdist pattern: suffix the DB path with `os.environ.get('PYTEST_XDIST_WORKER', '')`, e.g. `test_playwright_db_gw0.sqlite3`), so parallel workers cannot corrupt or lock against each other's fixture state.
3. Wire `-n` into the Makefile targets (`test-playwright`, `test-playwright-core` at minimum) with a sensible default (e.g. `-n auto` or a number tuned to avoid the exact resource-contention problem #1468 also addresses — do not simply default to one worker per core if that recreates oversubscription risk under concurrent agents; consider an env-var override so CI/local can tune independently).
4. Verify correctness, not just speed: run the full core subset with the new parallelism enabled at least twice back-to-back and confirm identical pass/fail results both times (no new flakiness from cross-worker state leakage), and confirm the WorktreeGuard still correctly blocks a genuinely separate concurrent invocation (e.g. two `make test-playwright-core` runs started independently in the same worktree, not from one `-n` invocation).
5. Measure and report the actual wall-clock improvement on this repo's real core subset (906 tests), not a theoretical estimate.
6. Update `_docs/testing-guidelines.md` with the new expected runtime and any new env vars.
7. Decide whether CI's `ci.yml` playwright job (currently serial) should also get `-n`, given it runs on a different (likely smaller/differently-provisioned) GitHub Actions runner than local dev boxes — a blanket `-n auto` there could misbehave on a constrained CI runner. Default to leaving CI as-is unless research shows it's clearly safe and beneficial there too; local Makefile targets are the priority.

## Acceptance criteria

- [x] Root cause of why xdist was never wired in is understood and documented (dead dependency, incomplete migration, or a known blocker) — check git history/blame on the dependency addition and `PlaywrightWorktreeGuard` for context before implementing
- [x] Per-xdist-worker SQLite DB isolation implemented and does not break the existing per-worktree isolation (#885's fix) or the guard-blocks-second-invocation behavior
- [x] `make test-playwright-core` and `make test-playwright` accept parallelism, default to something safe (documented reasoning for the chosen default/env-var) — both targets default to `-n 4 --dist loadfile`; core and full runs verified green repeatedly
- [x] Two consecutive full core-subset runs with parallelism enabled produce identical pass/fail results (no flakiness introduced)
- [x] A genuinely separate second concurrent `make test-playwright-core` invocation in the same worktree is still correctly blocked by the guard
- [x] Real measured wall-clock time for the 906-test core subset reported in the issue, before and after
- [x] `_docs/testing-guidelines.md` updated
- [x] `uv run ruff check .` clean; relevant Django/pytest tests for any conftest/guard changes pass

## Dependencies

None. May want to land after or alongside #1468 (affected-tests scoping) since both target per-issue verification speed, but they're independent changes touching different files (#1468: scripts/, agent defs, docs; this: playwright_tests/conftest.py, playwright_tests/worktree_guard.py, website/settings.py, Makefile).

**Comment by alexeygrigorev** [comment]
## Software Engineer Report

Worktree for the tester: `/data/agents/ai-shipping-labs/worktrees/swe-1470` (branch `worktree-agent-1470`). Not committed.

### Root cause: why xdist was never wired in

`git log -S"pytest-xdist" -- pyproject.toml` returns exactly one commit: `3139c6cb` "Add live LLM-judge test set for the AI assistants" (#811). pytest-xdist was added for `make test-judge` (`pytest -m live_judge tests/live_judge/ -n 4`), which is the only invocation that has ever used `-n`. The `# parallelizes the Playwright test run` comment in `pyproject.toml` was aspirational and never true — this is a mislabeled dependency, not an abandoned migration or a known blocker.

The real blocker for turning it on was #1151 (`871f4fff`), which added `PlaywrightWorktreeGuard`. The guard takes an exclusive `flock` on `.tmp/playwright-session.lock` in `pytest_sessionstart`. Every xdist worker is a full pytest session in its own subprocess and runs `pytest_sessionstart` too, so `pytest -n 4` would have deadlocked against its own controller: the controller claims the lock, then each of the 4 workers hits `WorktreeGuardAlreadyHeld` and `pytest.exit(returncode=2)`. Second blocker: `test_playwright_db.sqlite3` had no per-worker suffix, so had the guard let the workers through they would have migrated, seeded, and truncated the same SQLite file.

### Files modified

- `playwright_tests/worktree_guard.py` — new `current_xdist_worker_id()` / `is_xdist_worker()` reading `PYTEST_XDIST_WORKER`, with filesystem sanitization of the id.
- `playwright_tests/conftest.py` — `playwright_test_database_name()` + `apply_playwright_test_database()` (per-worker SQLite file); `_claim_playwright_worktree_guard()` now returns early in worker processes.
- `Makefile` — `PLAYWRIGHT_XDIST_WORKERS ?= 4` and `PLAYWRIGHT_XDIST_FLAGS = -n $(PLAYWRIGHT_XDIST_WORKERS) --dist loadfile`, applied to `test-playwright` and `test-playwright-core`.
- `playwright_tests/test_worktree_session_guard.py` — 20 new pure tests for worker detection, DB naming, and the guard-claim decision; one existing test now pins controller behavior explicitly.
- `playwright_tests/test_studio_user_merge.py`, `playwright_tests/test_issue_1288_user_support.py` — two pre-existing load-sensitive races fixed (details below).
- `_docs/testing-guidelines.md`, `_docs/PROCESS.md` — new runtime expectation, env var, and isolation contract.

### Guard: worker-aware, second invocation still blocked

Only the controller claims the lock. Workers detect `PYTEST_XDIST_WORKER` and skip. A genuinely separate invocation can never smuggle workers past the guard, because its own controller — which never has `PYTEST_XDIST_WORKER` set — fails before spawning any.

Verified live, with a real `-n 4` run holding the lock in the same worktree:

| Second invocation | Result |
|---|---|
| `uv run pytest -m "core and not visual_regression" playwright_tests/ -q` (serial) | blocked, `Exit: Another Playwright session is already using this worktree.` |
| `uv run pytest ... -n 4 --dist loadfile -q` (parallel) | exit 2, blocked, zero `gw*` worker output — no workers spawned |
| `make test-playwright-core` | exit 2, blocked |

### Database isolation

`test_playwright_db_gw0.sqlite3` … `test_playwright_db_gw3.sqlite3`, confirmed on disk during a live run. Serial runs and the controller keep the unsuffixed `test_playwright_db.sqlite3`, so #885's per-worktree isolation is unchanged — the suffix is applied under `BASE_DIR`, which is already per-worktree. `*.sqlite3`, `*.sqlite3-shm`, and `*.sqlite3-wal` are already gitignored. The name still contains `test`, so `website.test_database_guard.assert_playwright_database_is_safe` continues to accept it (asserted in a test).

### Port fixture: verified, not assumed

Empirically confirmed per-worker: each worker's `django_server` yielded a distinct port (e.g. `http://127.0.0.1:46813` on gw0 while siblings ran elsewhere). No conftest change was needed here. `PLAYWRIGHT_DJANGO_PORT` pins one port and therefore does not combine with `-n`; documented.

### Worker default: 4, not `-n auto`

`-n auto` would be 12 on this box. Each worker is a Chromium process tree plus an in-process Django server, and several agents run Playwright concurrently from separate worktrees — load average was 39-54 throughout this work. 4 matches the CI shard count and the existing `make test-judge -n 4`. Override with `PLAYWRIGHT_XDIST_WORKERS=N`; `0` disables xdist entirely.

`--dist loadfile` keeps each module on one worker: preserves intra-module ordering assumptions, avoids repeated per-module setup, and mirrors how `deploy-dev.yml` already shards by file. Largest core module is 40 of 906 tests, so imbalance is bounded.

### Measured wall clock (real runs, not estimates)

| Run | Mode | Wall clock | Result |
|---|---|---|---|
| Baseline (from this issue) | serial | 93.7 min / 92.9 min | — |
| Run 1 | `-n 4 --dist loadfile` | 22.6 min | 920 passed, 4 failed |
| Run 2 | `-n 4 --dist loadfile` | 15.6 min | 925 passed, 0 failed |
| Run 3 | `-n 4 --dist loadfile` | 14.3 min | 925 passed, 0 failed |

Runs 2 and 3 are the back-to-back consecutive pair required by the acceptance criteria. Comparing their JUnit XML node-by-node: 925 nodes each, identical node sets, zero status differences, all passed. No cross-worker flakiness.

Measurement caveat: every run above was taken under real concurrent load from other agents (load average 39-54 on a 12-core box, including other worktrees' Playwright suites). Run 1's 22.6 min was the most contended. The numbers are therefore conservative; an idle box should be at least this fast.

### The 4 failures in run 1, and what they were

Two were my own harness bugs, fixed:

1. `test_serial_run_keeps_the_historical_database_name` — passed `worker_id=None` meaning "serial", but `None` was also the "read the environment" default, so under xdist it read the ambient worker. Introduced an explicit `_AMBIENT_WORKER` sentinel so `None` unambiguously means serial.
2. `test_sessionstart_claims_guard_for_local_direct_pytest` (pre-existing) — asserts controller behavior, so it now `delenv`s `PYTEST_XDIST_WORKER`.

Two were pre-existing product/test races that pass serially and go red on a loaded box. Both were confirmed as such by running them serially (both passed) before fixing:

3. `test_issue_1288_user_support.py::test_alias_add_remove_and_conflict` — asserted `locator.is_visible()` immediately after a form submit. `is_visible()` does not auto-wait, so it raced the POST/redirect. Now waits for the conflict message with `SETTLE_TIMEOUT_MS`.
4. `test_studio_user_merge.py` (4 tests) — the merge page's typeahead renders an `absolute z-20` suggestion list directly over the "Preview merge" button, and hit-testing then blocks the click for the full 30s timeout. Extracted `_fill_merge_form_and_preview()`, which lets both debounced searches settle and then blurs each input once more so no late `render()` can re-show a list before the click. Still a real button click through the real form — no `force=True`.

### Product bug found (NOT fixed here — needs its own issue)

`templates/studio/users/merge.html`: `hide()` on the typeahead only runs from the input's own `blur` handler, so a debounced `/studio/api/users/search/` response that resolves after the blur re-shows the suggestion list with no further blur left to close it. The list is `absolute z-20` and sits over the submit button, so a real operator who types in the canonical field and tabs away can end up unable to click "Preview merge". The same `render()` pattern (no `document.activeElement` check) exists in `templates/studio/includes/_people_picker.html`, `templates/studio/courses/enrollments_list.html`, and `templates/studio/courses/access_list.html`. One-line fix each (`if (document.activeElement !== input) { hide(); return; }`), deliberately left out of scope for an infra issue.

### Repo trap found (NOT fixed here — needs its own issue)

Adding ANY new file under `playwright_tests/test_*.py` breaks two core Django tests: `tests.test_scheduled_playwright_balancing` hard-pins `loads_ms`, per-shard file counts, and the round-robin baseline derived from the on-disk Playwright file inventory. No Playwright file has been added since that manifest landed (`068d6e60`, 2026-08-13), so there is no precedent for updating those constants. I worked around it by merging the new #1470 tests into the existing `playwright_tests/test_worktree_session_guard.py` rather than adding a file — the right home for them anyway — but the next person to add a Playwright test file will hit this with no documented remedy.

### CI left serial (deliberate)

`ci.yml`'s `playwright-tests` job and `deploy-dev.yml`'s `playwright-core` matrix are unchanged. `deploy-dev.yml` already parallelizes across 4 GitHub Actions runners (one process per runner), and GitHub-hosted runners are 2-4 vCPU. Adding intra-job `-n` on top of the shard matrix would oversubscribe each runner rather than speed it up, and would multiply per-worker migration cost on machines that have no spare cores. `-n` is a local-dev lever only. This matches the issue's stated default.

### Tests

- New/changed pure tests: 20 new in `playwright_tests/test_worktree_session_guard.py` (37 total in that module + `test_conftest_port_resolution.py`). Pass serially and under `-n 2`.
- Playwright core subset: 925 passed, twice consecutively, identical results.
- Django full suite (`make test`): `Ran 14722 tests ... OK (skipped=2)`.
- `uv run ruff check .`: clean.

### Design-System Conformance

No template markup was changed and no new class-string pattern was introduced. `_docs/design-system.md` ("Before You Write a Class String", "Partials and Component Index", "Form Controls") was read as pre-work while evaluating a candidate fix to `templates/studio/users/merge.html`; that fix was ultimately not made and the template is untouched in this diff.

### Known limitations

- 4 workers is a heuristic default tuned for a shared 12-core box, not a measured optimum. `PLAYWRIGHT_XDIST_WORKERS=8` was not benchmarked.
- `PLAYWRIGHT_DJANGO_PORT` and `-n` are mutually exclusive by construction (one pinned port, N servers). Documented, not enforced with an error.
- `make test-playwright-manual-visual` and `make test-visual-regression` were left serial: they are on-demand screenshot/manual-review targets, not the per-issue verification hot path.

**Comment by alexeygrigorev** [comment]
## QA Review

Verdict: FAIL — one blocking issue. The parallelization mechanism itself (guard, per-worker DB, Makefile wiring) is correct and I reproduced every claim about it independently. The blocker is that wiring `-n 4` into `make test-playwright` (full suite) turns that target red.

### Test Summary

| Layer | Result |
| --- | --- |
| Focused Django tests (`tests.test_database_guard`, `tests.test_ci_pytest_timing`, `tests.test_tailwind_build`) | 9 passed / 0 failed |
| Playwright guard unit tests standalone (`test_worktree_session_guard.py`) | 27 passed / 0 failed |
| Playwright E2E core — `make test-playwright-core` (`-n 4`, my independent run) | 925 passed / 0 failed, 13:01 |
| Playwright E2E full — `make test-playwright` (`-n 4`, escalated per PROCESS.md because the diff touches `playwright_tests/conftest.py`) | 2470 passed / 10 failed / 1 skipped, 37:23 |
| `uv run ruff check .` | clean |
| Full Django suite / coverage | deferred to CI |

### Blocking issue: `make test-playwright` is red under the new `-n 4` default

`make test-playwright` on this branch: `10 failed, 2470 passed, 1 skipped in 2243.14s (0:37:23)`.

```
FAILED playwright_tests/test_dev_smoke_pricing.py::test_pricing_page_renders_tier_grid
FAILED playwright_tests/test_plan_sprints_ingest_889.py  (4 tests)
FAILED playwright_tests/test_testimonials_layout.py::test_homepage_testimonials_desktop_and_mobile_screenshots
FAILED playwright_tests/test_workshop_copy_file.py  (4 tests)
```

Same branch, same box, same command, only `PLAYWRIGHT_XDIST_WORKERS` differs:

- `PLAYWRIGHT_XDIST_WORKERS=0 make test-playwright` → `test_dev_smoke_pricing.py::test_pricing_page_renders_tier_grid PASSED [ 0%]` (it is the 3rd test in the alphabetical serial order).
- `make test-playwright` (`-n 4`) → same test runs 86th on `gw1` and fails with `AssertionError: Expected tier cards ['basic', 'free', 'main', 'premium'], found []`.

Root cause: `--dist loadfile` changes execution order. 83 of the 85 files `gw1` ran before `test_dev_smoke_pricing.py` use `@pytest.mark.django_db(transaction=True)`, which truncates tables. That module's `_ensure_tiers_seeded` autouse fixture re-seeds `Tier` inside a non-transactional `django_db` transaction that the in-process `runserver` thread cannot see, so it only survives when the module runs early. The other three modules are the same class of order fragility:

- `test_workshop_copy_file.py`: `AssertionError: [{'error': 'AuthorizationHeaderMalformed ... ListObjectsV2 ... non-empty Access Key (AKID)', 'step': 's3_list'}]` — the sync pipeline sees a configured `AWS_S3_CONTENT_BUCKET` with empty credentials.
- `test_plan_sprints_ingest_889.py`: `AttributeError: 'NoneType' object has no attribute 'threads_persisted' / 'replies_added' / 'members_matched'`, plus `slack-ingest-unmatched-thread` count 0.

All 10 pass in isolation (I ran exactly those 10 serially: `12 passed in 155.30s`) and in small serial groups, so they are order-dependent, not environment-dependent.

Secondary concern: `--dist loadfile` assigns files to workers as workers free up, so the file→worker grouping is timing-dependent, not deterministic. The core subset happens to be immune (3/3 identical runs below), but the full target now has a non-deterministic failure set.

Required before approval, in order of preference:

1. Make the four order-fragile modules order-independent (commit the seeded rows so the `runserver` thread can see them — e.g. `transaction=True`, or seed outside the test transaction), then run `make test-playwright` green twice.
2. If that is out of scope: leave `test-playwright` (full) serial, apply `$(PLAYWRIGHT_XDIST_FLAGS)` only to `test-playwright-core`, file a follow-up for the order-fragile modules, and document the limitation in `_docs/testing-guidelines.md`. This weakens acceptance criterion 3, so it needs PM/orchestrator sign-off.
3. Not acceptable: skipping or xfailing the 10 tests.

### Acceptance criteria

- [x] PASS — Root cause understood and documented. Verified independently: `git log -S'pytest-xdist' -- pyproject.toml` → `3139c6cb Add live LLM-judge test set for the AI assistants`, which added `make test-judge: uv run pytest -m live_judge tests/live_judge/ -n 4`. The `pyproject.toml` comment "parallelizes the Playwright test run" was a mislabel.
- [x] PASS — Per-xdist-worker SQLite isolation. After a `-n 4` run the worktree contains exactly `test_playwright_db_gw0..gw3.sqlite3` (+ `-wal`/`-shm`), and no unsuffixed `test_playwright_db.sqlite3`. Serial runs keep the unsuffixed name (`test_serial_run_keeps_the_historical_database_name`). All files stay under `BASE_DIR`, so #885 per-worktree isolation is intact, and worker ids are sanitized to `[A-Za-z0-9_-]` (`../../etc/gw0` → `etcgw0`). `.gitignore` already covers `*.sqlite3`, `*.sqlite3-wal`, `*.sqlite3-shm`.
- [ ] FAIL — `make test-playwright-core` and `make test-playwright` accept parallelism. Core is correct and green; full is red (above). `PLAYWRIGHT_XDIST_WORKERS=0` was verified end-to-end (`uv run pytest ... -n 0 --dist loadfile -v` runs serially, exit 0). Default of 4 rather than `-n auto` is well reasoned for this box.
- [x] PASS — Two consecutive core runs identical. Three now. `run2` 925/0/0/0 in 931.8s, `run3` 925/0/0/0 in 856.0s (SWE), and my independent `make test-playwright-core` 925/0/0/0 in 781.5s. I parsed all three JUnit XMLs: node sets are set-equal, symmetric difference empty. Worker balance is near-ideal: 3071s of test time across 4 workers = 768s theoretical, 781s actual.
- [x] PASS — A genuinely separate second invocation is still blocked. Verified live against a running `-n 4` core run holding the lock, not taken on trust:
  - serial second invocation → exit 2, holder reported as the running controller PID.
  - `-n 4` second invocation → exit 2, and only ONE PID appears in the guard output, so zero workers were spawned.
  - For contrast I accidentally ran the same `-n 4` command against an unpatched checkout: dozens of distinct worker PIDs cycled through the guard and the run ended `exit 5, no tests collected`. That is exactly the failure mode the worker exemption prevents, so the fix is load-bearing, not cosmetic.
- [x] PASS — Real measured wall clock reported. Serial baseline 93.7 / 92.9 min; `-n 4` 15.6 / 14.3 min (SWE) and 13.0 min (mine).
- [x] PASS — `_docs/testing-guidelines.md` updated (two accuracy nits below).
- [x] PASS — `uv run ruff check .` clean; guard/conftest tests pass (27 standalone, and all 27 also pass from inside real xdist workers in the core run — `test_sessionstart_claims_guard_for_local_direct_pytest` correctly `delenv`s the ambient `PYTEST_XDIST_WORKER`).

### The two "pre-existing race" test fixes — legitimate, not masking

- `test_issue_1288_user_support.py`: replacing a bare `is_visible()` (which does not auto-wait) with `wait_for(state="visible", timeout=SETTLE_TIMEOUT_MS)` before asserting. Textbook fix, no coverage lost.
- `test_studio_user_merge.py`: the underlying defect is real and correctly diagnosed. `templates/studio/users/merge.html` hides the typeahead list only from the input's own `blur` handler via `setTimeout(hide, 150)`; a debounced `/studio/api/users/search/` response that resolves after that timer calls `render()` and re-shows an `absolute z-20` list over the "Preview merge" button with no further blur left to close it. The harness works around it by ordering (settle both searches, blur both inputs, then assert both lists are `hidden`) and still submits via `settle_click`, which uses a normal actionability-checked `click()` — no `force=True`. If the dropdown were genuinely stuck the test would still fail, and every merge assertion is unchanged. Not masking.

Reliability check, run in isolation on this branch:
- fixed versions: 3 consecutive runs, `17 passed` each (227s / 184s / 196s).
- pre-fix versions (reverted to `HEAD`): 2 consecutive runs, `17 passed` each (295s / 229s).

That confirms the SWE's account: both are load-sensitive waiting races that only surface under `-n 4` concurrency, not product regressions. The working tree was restored afterwards and the restored patch is byte-identical to the original.

### CI-serial reasoning — decision sound, justification partly wrong

Leaving CI serial is the right call and matches the issue's stated default. `deploy-dev.yml`'s `playwright-core` job is a 4-way file-shard matrix, one `ubuntu-latest` runner per shard, so intra-job `-n` on a 2-4 vCPU runner would oversubscribe rather than help.

But `_docs/testing-guidelines.md` says "`.github/workflows/ci.yml` and `deploy-dev.yml` already parallelize across GitHub Actions runners (a 4-way shard matrix, one runner per shard)". That is not true of `ci.yml`: its 4-way shard matrix is the Django `test` job. Its `playwright-tests` job (line 339) is a single unsharded runner running `uv run pytest -m "not manual_visual and not visual_regression" playwright_tests/ asl_cli/ -v`. Worth also noting `ci.yml` only triggers on `pull_request` and this repo does not use PRs, so that job effectively never runs. Please correct the sentence.

### Other non-blocking issues

- `_docs/testing-guidelines.md` says the core subset is "906 tests" in three places. Measured count on this branch is 925 (380 files, largest module 40 tests). Suggest "~925" or a non-numeric phrasing so it does not go stale again.
- `PLAYWRIGHT_DJANGO_PORT` combined with `-n > 0` would make every worker bind the same port. This is documented as "does NOT combine" but not enforced; consider failing fast in `pytest_configure` when both are set.
- `playwright_tests/test_studio_user_merge.py` now has two consecutive `from playwright_tests.conftest import (...)` statements; they could be merged. Cosmetic.
- The worktree HEAD is 7 commits behind `origin/main`. None of those 7 commits touch the 8 changed files, but they do add and modify Playwright test modules, so the 925 core count will change after rebase — re-verify the core run post-rebase.

### Design-system check

No `*.html` files changed (tracked or untracked), so all three forbidden-pattern scans and the untracked-template scan are vacuously clean.

**Comment by alexeygrigorev** [comment]
## Screenshots

No templates changed in this diff, so these are context shots for the two surfaces exercised by the "pre-existing race" test fixes. Captured on a dedicated free port rather than via `scripts/capture_screenshots.py`, because that script hardcodes port 8766 and on this box 8766 is currently held by an unrelated repo's `runserver` (`/home/alexey/git/dtc-website`) — using it would have screenshotted the wrong site.

- `/studio/users/merge/` (desktop 1280x720, logged in as designer-staff@example.com): https://d31nukezbn4e3o.cloudfront.net/2026/08/26/35a372f6f29c4704a71b507904ed872c-f91d146e829e2824.png
- `/studio/users/` (desktop 1280x720, logged in as designer-staff@example.com): https://d31nukezbn4e3o.cloudfront.net/2026/08/26/37135de26fdc4933a63501aba895d303-1ec9e899ebf579a4.png

Both returned HTTP 200 and render correctly. The "Environment mismatch" banner and the analytics consent dialog are expected local-dev artifacts.

**Comment by alexeygrigorev** [comment]
## Ship handoff

Implemented and merged as `e238f4bf44411cd7d8d50d59b3359acc38aa4c64`. Local Playwright targets now default to `-n 4 --dist loadfile` with per-worker SQLite DBs, worker-aware guard/cache isolation, safe overrides, and the load-sensitive test fixes. QA and PM acceptance passed; repeated full/core artifacts were green. Deploy Dev run [33052055920](https://github.com/AI-Shipping-Labs/website/actions/runs/33052055920) is green with all 10 required jobs.
