### ISSUE TITLE
CI: Deploy Dev test job cancelled at 30m timeout despite passing suite

### ISSUE THREAD

**Issue by alexeygrigorev** [AI-Shipping-Labs/website#888]
# CI: Deploy Dev test job cancelled at 30m timeout despite passing suite

Status: pending
Tags: `infra`
Depends on: None
Blocks: —

## Summary

Deploy Dev run `27158919559` (commit `70d4a379`, the #887 Slack-fix merge) was cancelled — not failed. The `Unit & Integration Tests` job in `deploy-dev.yml` hit its `timeout-minutes` cap and GitHub cancelled it, which skipped `Deploy to Dev`. The suite had actually passed: `Ran 9908 tests in 1760.045s ... OK`, then `##[error]The operation was canceled.`. All other gates passed (missing-migrations, OpenAPI drift, system checks, collectstatic). This is a CI-capacity problem, not a code defect.

## Current state (already partially mitigated)

The stopgap from the original report is already in the tree — do not redo it:

- `deploy-dev.yml` (line 29) test job is already at `timeout-minutes: 45` (bumped from 30 with an inline comment referencing this issue).
- The test step already runs `uv run python manage.py test --parallel 4 --exclude-tag=visual_regression --keepdb`, with a cached, validated file-backed SQLite test DB (`actions/cache@v5`, key hashed on migration files).
- A custom runner (`website/test_runner.py::PicklableTracebackRunner`) keeps `--parallel` stable (tblib traceback pickling, refs #762).
- Coverage is NOT on the CI critical path. `coverage run manage.py test` exists only as a local `make coverage` target (single-process, ~33m locally). CI never invokes coverage, so option (d) "drop coverage from critical path" is already satisfied — nothing to do there.

So the remaining problem is the deeper signal flagged in the report: the suite runtime (~1760s ≈ 29.3m pure runtime, ~9908 tests and growing as every issue adds tests) is creeping toward the cap. The 45m bump buys headroom but each new issue erodes it. We want the suite to actually be faster, with durable headroom — not just a higher ceiling.

## Recommended approach

Make the suite faster, then keep the timeout as a generous safety net. Two complementary levers, in priority order:

1. Shard the Django test suite across parallel jobs (matrix fan-out). This is the durable fix — it scales with the suite instead of fighting it. Split the suite into N shards (start with N=4) that run as a matrix of jobs, each on its own runner. Each shard runs a disjoint subset of tests; the `deploy` job gates on all shards passing. With N=4 each shard runs ~1/4 of the wall time (~7-8m of test runtime + ~2-3m setup), so the slowest shard finishes well under the cap with large headroom, and the suite stays under the cap even as it grows.

2. Right-size intra-job parallelism. GitHub-hosted `ubuntu-latest` runners are 4 vCPU (the 12 vCPU on the dev box is irrelevant). `--parallel 4` is reasonable for a 4-vCPU runner; when combined with sharding, set each shard's `--parallel` to the shard's vCPU count (or `--parallel auto`/`$(nproc)`), so the two levers compound rather than oversubscribe. Do NOT raise `--parallel` beyond the runner's vCPU count on a single job — that thrashes and can slow the suite.

The implementer may use either Django's built-in test-label partitioning or a deterministic shard-assignment helper, but sharding MUST be deterministic and disjoint (every test runs exactly once across all shards; no test runs twice; no test is dropped). Total test count summed across shards must equal the single-job count.

Rejected / lower-priority alternatives, for the record:
- (c) Raise `timeout-minutes` further as the primary fix — rejected. Already at 45m; raising it again just defers the problem and widens the #269 hang blast radius. Keep 45m (or set a per-shard cap, e.g. 20m, since each shard is much shorter) as the safety net, not the fix.
- (d) Move coverage off the critical path — N/A, coverage is already local-only.
- A single larger runner (e.g. `ubuntu-latest-4-core` / bigger) instead of sharding — acceptable as a secondary speedup but does not scale as cleanly as sharding and may incur cost; sharding on standard runners is preferred. If the implementer finds sharding setup overhead (uv sync + browserless setup) dominates, a larger single runner with higher `--parallel` is an acceptable fallback, but must still hit the headroom target below.

## Scope

- Workflow: `.github/workflows/deploy-dev.yml`
  - Convert the `test` job into a sharded matrix (default `shard: [1, 2, 3, 4]` of `total: 4`), OR keep a single job on a larger runner with `--parallel` matched to vCPUs — implementer's choice, but the matrix shard approach is recommended.
  - Each shard runs the full pre-test gate set it needs to be valid in isolation, OR factor the one-time gates (missing-migrations check, OpenAPI drift check, system checks, collectstatic) into a separate fast `checks` job so they run once, not once per shard. Recommended: a single lightweight `checks` job for the non-test gates, plus the sharded `test` matrix for the tests. Keep CI_TIMING profiling lines on each job.
  - Preserve the cached, validated file-backed SQLite test DB per shard (`--keepdb`, `DJANGO_TEST_DB_NAME=test_db.sqlite3`, cache key on migration-file hash). Each shard may use its own cache path/key suffix to avoid cache-save contention.
  - `deploy` job `needs:` must list every shard job (and the `checks` job and `playwright-core`) so deploy only runs when all shards are green.
  - Set a per-shard `timeout-minutes` that is generous relative to a single shard's expected runtime (e.g. 20m) — the #269 hang safety net still applies per shard and the per-shard blast radius is naturally smaller.
- Workflow: `.github/workflows/ci.yml` (PR workflow)
  - Apply the same fix. Its `unit-tests` job is still at `timeout-minutes: 30` and runs the same growing `--parallel 4` suite, so it is the next job to hit the wall. Shard it the same way (or share a reusable workflow / composite to avoid duplication). Keep its PR-only extra gates (ruff lint, advisory lint) on the `checks`/single job, not duplicated per shard.
- No application code changes are required. If a small shard-assignment helper or a `manage.py` test-label wrapper is added, it lives under the existing test tooling (e.g. alongside `website/test_runner.py`) and must be covered by the determinism check above.
- Document the sharding in the workflow comments (why sharded, how shards are assigned, how to change N) following the existing inline-comment convention in these workflows.

## Acceptance Criteria

- [x] The Django test suite in `deploy-dev.yml` is sharded across a matrix of jobs (default 4 shards) OR runs on a larger single runner with `--parallel` matched to vCPUs; the chosen approach is documented in a workflow comment.
- [x] Sharding is deterministic and disjoint: across all shards every test runs exactly once. The sum of per-shard `Ran N tests` counts equals the single-job count (~9908+), with no test run twice and none dropped.
- [x] The slowest individual test shard (or the single job, if not sharded) completes with at least 40% headroom below its `timeout-minutes` cap on a normal GitHub-hosted runner (e.g. slowest shard ≤ ~12m against a 20m cap).
- [x] The full suite still runs (no `--exclude` added beyond the existing `visual_regression` tag; no tests skipped to hit timing).
- [x] The non-test gates (missing-migrations check, OpenAPI drift check, Django system checks, collectstatic) still run on every deploy, either once in a dedicated `checks` job or per shard — and a failure in any of them still blocks deploy.
- [x] The `deploy` job `needs:` includes every shard job plus `playwright-core` (and the `checks` job if introduced); deploy runs only when all are green and is still gated on `github.ref == 'refs/heads/main'`.
- [x] Each shard keeps the cached, validated file-backed SQLite test DB (`--keepdb`), with cache keys that do not collide across shards.
- [x] `ci.yml` (PR workflow) gets the same sharding treatment; its `unit-tests` job no longer runs the entire ~1760s suite in one job under a 30m cap.
- [x] `timeout-minutes` is retained as a safety net (per-shard, e.g. 20m, or job-level) — the #269 django-q hang blast radius stays well under the historical ~1h40m worst case.
- [x] CI_TIMING profiling lines are preserved on the test jobs so future runtime creep is observable.
- [ ] [HUMAN] A green `deploy-dev.yml` run on a real push to `main` completes all shards under their caps and proceeds through `Deploy to Dev` to a successful `/ping` version match (the run is not cancelled).
- [ ] [HUMAN] A failing test (introduce a deliberate failure on a branch) still fails its shard, blocks deploy, and surfaces the failure traceback — i.e. sharding did not reintroduce the #762 masked-failure behaviour.

## Test Notes (CI-infra task — no Playwright user scenarios)

This is a DX/infra change with no user-facing surface, so there are no Playwright user-journey scenarios. Verification is via CI behaviour and the existing Django suite:

- The existing Django suite (`make test` / `--parallel`) must still pass unchanged after any helper is added; the determinism check (sum of shard counts == single-run count) is the key new assertion and can be verified by summing the `Ran N tests` lines across shard logs in a run.
- The two `[HUMAN]` criteria above (green deploy run not cancelled; deliberate failure still blocks + surfaces traceback) are the acceptance gates a reviewer runs against a real workflow run.
- The tester/reviewer should confirm via the CI_TIMING lines that the slowest shard sits comfortably under its cap (headroom criterion).

---

Blocked by: (none)

**Comment by alexeygrigorev** [comment]
## Grooming Complete

### Summary
The Deploy Dev test job was cancelled at its timeout cap even though the suite passed (`Ran 9908 tests ... OK`), skipping deploy. The 30->45m stopgap from the original report is already merged into `deploy-dev.yml`, so grooming refocuses this on the deeper signal: a ~1760s (~29m) and still-growing Django suite needs to get faster, not just be allowed to run longer.

### Key Decisions
- The proposed timeout bump (30 -> 45m) is already in `deploy-dev.yml` (line 29) — do not redo it. Keep 45m (or a smaller per-shard cap) as the #269 hang safety net, not as the fix.
- Recommended fix: shard the Django suite across a 4-job matrix (durable, scales with the suite), with `--parallel` matched to each runner's vCPU count. A larger single runner is an acceptable fallback but does not scale as cleanly.
- `--parallel 4` and the cached file-backed `--keepdb` SQLite DB and `PicklableTracebackRunner` (#762) are already in place — preserve them, don't reinvent.
- Coverage option (d) is moot: coverage is local-only (`make coverage`), never on the CI critical path.
- Pulled `ci.yml` into scope too — its PR `unit-tests` job is still at 30m running the same growing suite, so it's the next to hit the wall.
- Factor the one-time gates (missing-migrations, OpenAPI drift, system checks, collectstatic) into a single `checks` job so they don't run once per shard.

### Dependencies
- None. Self-contained CI workflow change; no app code required (a small deterministic shard-assignment helper is optional and lives with `website/test_runner.py`).

### Test Notes
- Infra/DX task — no Playwright user scenarios. Acceptance hinges on two `[HUMAN]` checks: a real green push to `main` completes all shards under cap and deploys (not cancelled), and a deliberate failure still fails its shard, blocks deploy, and surfaces the traceback (no #762 regression). Plus the determinism invariant: summed per-shard test counts == single-run count, no test run twice or dropped.

### Open Questions
- None blocking. Implementer chooses matrix-shard vs larger-single-runner; matrix sharding is the recommended default.

Ready for implementation.

**Comment by alexeygrigorev** [comment]
## Software Engineer Report

### Approach
Implemented the recommended matrix-shard fix (not just a timeout bump). The Django suite is fanned out across a 4-job matrix in both `deploy-dev.yml` and `ci.yml`. The one-time deploy/PR gates are factored into a dedicated `checks` job so they run once, not once per shard.

### Files Created/Modified
- `website/test_runner.py` — added deterministic, env-gated sharding to `PicklableTracebackRunner`. New helpers `_shard_for_test_id(test_id, N)` (SHA-256(test id) % N, 1-based) and `_read_shard_env()` (parses `TEST_SHARD_COUNT` / `TEST_SHARD_INDEX`, raises on invalid config). `build_suite` filters to this shard's subset after tag-filter + reorder but before parallel partitioning, so `--parallel` and `--exclude-tag=visual_regression` still apply per shard. When `TEST_SHARD_COUNT` is unset/<=1 the runner is identical to stock `DiscoverRunner` (local `make test` unchanged).
- `tests/test_test_runner_sharding.py` — new tests: determinism, 1-based in-range index, disjoint+complete partition (summed shard counts == single-run count, no dup/drop) across N=1,2,4,5,8, all-shards-non-empty, and `_read_shard_env` enable/disable/validation cases.
- `.github/workflows/deploy-dev.yml` — `test` converted to a `shard: [1,2,3,4]` matrix (`TEST_SHARD_COUNT=4`, `TEST_SHARD_INDEX=${{ matrix.shard }}`, `timeout-minutes: 20` per shard); per-shard cache key suffix `shard${{ matrix.shard }}` so concurrent shards don't race on cache save; one-time gates (missing-migrations, OpenAPI drift, system check, collectstatic) moved into a new `checks` job; `deploy.needs: [checks, test, playwright-core]`. CI_TIMING lines preserved and tagged with shard.
- `.github/workflows/ci.yml` — same sharding for `unit-tests`; PR-only gates (ruff, advisory lint, collectstatic, migrate, system check) moved into a `checks` job; `playwright-tests.needs: [checks, unit-tests]`.

### Why this fixes the 30m cancellation
The single-job suite was ~1760s pure runtime and growing (now 10336 tests locally). With N=4 deterministic shards each runs ~1/4 of the suite on its own runner, so the slowest shard's test runtime is ~7-8m + ~2-3m setup, comfortably under the 20m per-shard cap (>40% headroom). The suite stays under cap as it grows because adding tests spreads across all shards. The 45m single-job cap is replaced by a tighter per-shard 20m safety net, shrinking the #269 hang blast radius rather than widening it.

### Determinism / disjointness verified locally
Ran `notifications` (165 tests) single vs sharded N=3:
- single: `Ran 165 tests`
- shard 1/3: selected 56, shard 2/3: selected 50, shard 3/3: selected 59
- 56 + 50 + 59 = 165 — exact match, no test run twice, none dropped. Same id always lands in the same shard (SHA-256, no dependence on discovery order / PYTHONHASHSEED).

### Tests
- New sharding unit tests: 10 passing (`--parallel`).
- `make test-core`: `Ran 1451 tests in 50.5s ... OK`.
- Full Django suite (`--parallel --exclude-tag=visual_regression`): `Ran 10336 tests in 601.7s ... OK (skipped=1)` — unsharded behavior unchanged.
- `ruff check .`: clean.
- Both workflow YAMLs parse (`yaml.safe_load`); job graphs: deploy-dev = `checks, test, playwright-core, deploy`; ci = `checks, unit-tests, playwright-tests`.

### Notes
- No Playwright user surface; `make test-playwright-core` not required — sharding is Django-runner-only and inert under pytest (pytest-django doesn't use `PicklableTracebackRunner`).
- The two `[HUMAN]` criteria (real green `main` push not cancelled; deliberate failure still blocks + surfaces traceback) remain unchecked for human verification on a live run.

**Comment by alexeygrigorev** [comment]
## QA Review — FAIL

Critical bug: the sharding crashes in the exact CI configuration it ships for (`--parallel 4` full discovery). Every shard would die with `AttributeError` before running a single test — a hard CI break, not a false green.

### Root cause

`PicklableTracebackRunner.build_suite` calls `super().build_suite(...)` and then iterates the result calling `test.id()`:

```python
suite = super().build_suite(test_labels=test_labels, **kwargs)
...
for test in suite:
    if _shard_for_test_id(test.id(), count) == index:   # AttributeError here
```

But `DiscoverRunner.build_suite`, when `self.parallel > 1`, wraps the flat suite into a `ParallelTestSuite(subsuites, ...)` (see `if self.parallel > 1: subsuites = partition_suite_by_case(suite); ... suite = self.parallel_test_suite(subsuites, ...)`). Iterating that yields `TestSuite` subsuites, not flat `TestCase` objects, so `test.id()` raises:

```
File ".../website/test_runner.py", line 129, in build_suite
    if _shard_for_test_id(test.id(), count) == index:
AttributeError: 'TestSuite' object has no attribute 'id'
```

Reproduced live with the real CI command:
```
TEST_SHARD_COUNT=4 TEST_SHARD_INDEX=1 python manage.py test --exclude-tag=visual_regression --parallel 4
-> AttributeError: 'TestSuite' object has no attribute 'id'
```

This is why the unit tests and the per-app spot checks passed but CI would not: the helper tests (`tests/test_test_runner_sharding.py`) only exercise `_shard_for_test_id` / `_read_shard_env` directly and never go through `build_suite` with `--parallel > 1`; and small single-label runs (`python manage.py test payments`) happen to keep the suite flat. The failure mode is specific to `--parallel > 1` over the full suite — i.e. exactly the `deploy-dev.yml` / `ci.yml` test step.

### Fix direction

Shard the FLAT suite before Django wraps it for parallel. Options:
- Filter on `iter_test_cases(suite)` and rebuild a flat suite, leaving the `parallel > 1` wrapping to `super()` — i.e. shard inside an override that runs before the `ParallelTestSuite` wrap, or flatten with `django.test.runner.iter_test_cases` and re-run `partition_suite_by_case` yourself.
- Cleanest: override so the shard filter applies to the un-parallelized suite, then let the runner partition the filtered subset across workers.

The fix MUST be covered by a test that exercises `build_suite` with `--parallel 4` (or a constructed `ParallelTestSuite`), since the current tests miss this entire path.

### What I verified (passing in isolation)

- `tests/test_test_runner_sharding.py`: 10/10 pass — determinism, 1-based in-range, disjoint+complete partition for N in {1,2,4,5,8}, env-parse validation.
- Independent completeness on real test ids (payments app, via the helper): unsharded 254 unique ids; per-shard {1:76, 2:53, 3:63, 4:62}; sum 254; union size 254; overlap_dups 0; union == unsharded set. Identical shard map under default and `PYTHONHASHSEED=999` (hashseed-independent).
- End-to-end completeness for a single app at `--parallel 1`: `python manage.py test payments` sharded -> 76+53+63+62 = 254 = unsharded count.
- Misconfiguration fails loudly through the real runner (exit 1, no silent run): `TEST_SHARD_INDEX=5` (out of range) -> `ValueError: ... out of range`; `TEST_SHARD_INDEX=abc` -> `ValueError: invalid literal for int()`; `TEST_SHARD_COUNT=4` with index unset -> `ValueError: ... TEST_SHARD_INDEX is missing`.
- Default behavior unchanged (shard env unset): `make test-core` -> Ran 1451 tests, OK. Full suite `python manage.py test --exclude-tag=visual_regression --parallel` -> Ran 10336 tests, OK (skipped=1) — matches baseline exactly, no tests dropped.
- Both workflow YAMLs parse. Job graph correct: `deploy.needs = [checks, test, playwright-core]` (matrix `test` only succeeds when all 4 shards pass); `playwright-core` is separate; in ci.yml `playwright-tests.needs = [checks, unit-tests]`. Per-shard `timeout-minutes: 20`, `TEST_SHARD_COUNT=4`, `TEST_SHARD_INDEX=${{ matrix.shard }}`, per-shard cache key suffix, CI_TIMING lines preserved, deploy still gated on `github.ref == 'refs/heads/main'`.
- `make test-playwright-core`: 259 passed, 0 failed, 1099 deselected (core subset). Harness intact.

### Verdict: FAIL

The sharding logic is correct at the id-assignment level (disjoint, complete, deterministic, fails loud on misconfig), but `build_suite` crashes under `--parallel > 1` on the full suite — the actual CI configuration. Deploy/CI test shards would `AttributeError` before running any test. Fix the `build_suite` parallel-suite iteration and add a test that covers the `--parallel > 1` path, then re-review.

Acceptance criterion "Sharding is deterministic and disjoint ... sum of per-shard counts equals single-job count" is unchecked: the per-shard run cannot complete under `--parallel 4`, so the summed-count invariant cannot be demonstrated end-to-end in CI as shipped.

**Comment by alexeygrigorev** [comment]
## QA Re-Review (fix for the `--parallel 4` crash) — PASS

The prior FAIL was `PicklableTracebackRunner.build_suite` crashing under `--parallel > 1`: the parent returns a `ParallelTestSuite` of nested `TestSuite`s, and iterating it to call `test.id()` raised `AttributeError`, so every CI shard died before running a test. The SWE's fix flattens with `django.test.utils.iter_test_cases` (works for flat AND parallel-wrapped shapes), filters to the shard's ids, rebuilds a flat suite, then re-applies parallel wrapping (`partition_suite_by_case` + `parallel_test_suite`, `processes = min(self.parallel, len(subsuites))`). Verified the fix end-to-end with the exact CI command.

### 1. Each shard runs under `--parallel 4` (exact CI command), none crash

`TEST_SHARD_COUNT=4 TEST_SHARD_INDEX=$INDEX python manage.py test --exclude-tag=visual_regression --parallel 4`

| Shard | selected | Ran | Result | Wall |
|-------|----------|-----|--------|------|
| 1/4 | 2634 | 2634 | OK | ~3.4m |
| 2/4 | 2572 | 2572 | OK | ~3.2m |
| 3/4 | 2562 | 2562 | OK (skipped=1) | ~5.1m |
| 4/4 | 2572 | 2572 | OK | ~3.0m |

No `AttributeError`, no crash. `Test sharding active: shard X/4 selected N` log emitted on each. Slowest shard ~5.1m against the 20m cap (>40% headroom).

### 2. Completeness under parallel (the critical invariant)

Unsharded baseline (`--parallel 4`, no shard env): `Ran 10340 tests ... OK (skipped=1)`.

Sum of shards: 2634 + 2572 + 2562 + 2572 = 10340 == baseline. No test dropped or double-run. The single skipped test lands in shard 3 (so the skip is also not duplicated). Matches the SWE's reported numbers independently.

### 3. New `BuildSuiteShardingTests` genuinely exercise the parallel path

`tests/test_test_runner_sharding.py` (14 tests) passes under `--parallel 4`. Adversarial check: I temporarily reverted `build_suite` to the old buggy iteration — 3 of the 4 `BuildSuiteShardingTests` failed with the exact `AttributeError: 'TestSuite' object has no attribute 'id'`, then passed again on the fixed code. `test_unsharded_parallel_baseline` asserts the discovery target is large enough to wrap in a real `ParallelTestSuite`, so the regression path is genuinely covered (not a no-op).

### 4. Default (unsharded) unchanged

`TEST_SHARD_COUNT` unset: `make test-core` -> `Ran 1451 tests ... OK`, no "sharding active" log. Full unsharded baseline -> `Ran 10340 tests ... OK (skipped=1)`, matching the historical ~10336/10340 baseline.

### 5. Workflow job graph re-confirmed

- `deploy-dev.yml`: `deploy.needs: [checks, test, playwright-core]`, `deploy.if: github.ref == 'refs/heads/main'`. Matrix `shard: [1,2,3,4]`, `TEST_SHARD_COUNT=4`, `TEST_SHARD_INDEX=${{ matrix.shard }}`, per-shard `timeout-minutes: 20`, per-shard cache key suffix `shard${{ matrix.shard }}`. A failing test in any shard fails that matrix job, so `deploy` is blocked.
- `ci.yml`: `playwright-tests.needs: [checks, unit-tests]`, same `[1,2,3,4]` matrix, `timeout-minutes: 20`.
- Both YAMLs parse via `yaml.safe_load`.

### Test Summary
- Unit tests (sharding): 14 passed / 0 failed (`--parallel 4`)
- Full Django suite (baseline, `--parallel 4`): 10340 passed / 0 failed (skipped=1)
- 4 shards (`--parallel 4`): 2634 + 2572 + 2562 + 2572 = 10340, all OK
- `make test-core`: 1451 passed / 0 failed
- Playwright: not applicable (Django-runner-only change; inert under pytest)

### Acceptance Criteria
All non-`[HUMAN]` criteria verified, including the previously-failing determinism/disjoint criterion (now checked). The two `[HUMAN]` criteria (real green `main` push not cancelled; deliberate failure still blocks + surfaces traceback) remain unchecked for live verification.

### Verdict: PASS

The crash is fixed, the parallel path is covered by a regression test that fails on the old code, and the disjoint/complete invariant holds end-to-end under the exact CI configuration. SWE should commit.
