### ISSUE TITLE
Improve syllabus navigation spacing and mark-complete UI on mobile

### ISSUE THREAD

**Issue by alexeygrigorev** [AI-Shipping-Labs/website#483]
## Status
Groomed and ready for implementation.

## Background / Source
Raw feedback came from Google Recorder notes dated 2026-05-07 (`f6889920-d139-4f67-ab85-24a0b500b46e`, `636e25d3-d4be-4c9a-826d-9e31e008b487`). The concern is that course syllabus/module spacing is too large on mobile, workshop pages should feel structurally closer to courses, course navigation styles differ across contexts, mark-complete UI feels awkward on mobile, and zero-count announcement/progress text like `Catch announcement 0` should not show.

## Code Context Inspected
- Course detail syllabus accordion is in `templates/content/course_detail.html` under the `Syllabus` section.
- Course unit and workshop tutorial pages share reader partials: `templates/content/reader/_sidebar.html`, `_top_nav.html`, `_bottom_nav.html`, `_completion_button.html`, `_styles.html`, and `_scripts.html`.
- Course unit pages use `templates/content/course_unit_detail.html`; workshop tutorial pages use `templates/content/workshop_page_detail.html`.
- Completion toggle behavior is shared through `content/services/completion.py`, `content/views/courses.py::api_course_unit_complete`, and `content/views/workshops.py::api_workshop_page_complete`.
- Current bottom navigation renders previous link, completion button, and next link in one row/stack via `content/reader/_bottom_nav.html`.
- Announcement/banner context is exposed through `website/context_processors.py`; notification/announcement UI may be elsewhere, so the zero-count string needs a targeted search during implementation.

## Scope
- Tighten mobile spacing in course syllabus accordions and module/unit rows without reducing tap targets below 44px.
- Align course unit reader navigation and workshop tutorial reader navigation so equivalent actions look and behave the same.
- Improve mobile mark-complete placement and copy/state so it feels like an intentional inline action near the lesson/workshop content and bottom navigation.
- Preserve completion toggle semantics: course units still use `UserCourseProgress`; workshop pages still use `UserContentCompletion`.
- Suppress or reword zero-count announcement/progress copy so users never see awkward text like `announcement 0`, `0 announcements`, or similar where no actionable item exists.
- Keep desktop reader navigation and sidebars usable and dense enough for repeated learning workflows.

## Out Of Scope
- Changing access/gating semantics or public tier labels. See #481.
- Course/workshop catalog card responsiveness and duplicate page headings. See #480.
- Adding new completion concepts, certificates, or course progression rules.
- Replacing the shared reader/sidebar architecture wholesale.

## Acceptance Criteria
- [x] Course detail syllabus modules and unit rows are visibly tighter on mobile while maintaining at least 44px tap targets for interactive rows.
- [x] Course unit and workshop tutorial sidebars/mobile navigation use consistent typography, spacing, active state, completion icon, and collapse/open behavior where the structures are equivalent.
- [x] Mark-complete/Completed action is easy to find on mobile after reading the content and does not feel stranded between previous/next navigation.
- [x] Mark-complete button labels, completed state, loading/disabled state, and error handling remain accessible and clear on mobile and desktop.
- [x] Course unit completion still auto-enrolls through existing service behavior; workshop page completion still updates the shared completion service.
- [x] Previous/next navigation remains usable when titles are long and does not overflow on 320px/390px mobile widths.
- [x] Zero-count announcement/progress copy is hidden or grammatically correct wherever found; no user-facing `... 0` artifact remains.
- [x] Existing completion APIs continue returning the same JSON contract unless tests are intentionally updated with compatible behavior.

## Verification Plan
- Run focused Django tests for course units, workshop completion, dashboard/progress if affected, notification/banner tags if the zero-count text lives there, and completion service behavior.
- Run existing Playwright tests for course units, workshop completion, workshop tutorial sidebar, dashboard, announcement banner, and mobile resources accordion where applicable.
- Add or update Playwright screenshot scenarios for:
  - `/courses/<course_slug>` syllabus at 390x844 with multiple modules open/closed.
  - `/courses/<course_slug>/<module_slug>/<unit_slug>` at 390x844 before completion, after clicking Mark complete, and after reload.
  - Same course unit page at 1280x900 with sidebar visible.
  - `/workshops/<slug>/tutorial/<page_slug>` at 390x844 before/after completion and with mobile navigation opened.
  - Long previous/next titles on mobile for course unit and workshop page.
  - Any page where the zero-count announcement/progress artifact was reproduced.
- Verify screenshots show no overlap, no horizontal body overflow, visible focus states, and no broken/404 pages.

## Dependencies / Blockers
- Related to #480 for catalog/detail card and heading polish; no direct dependency.
- No external blockers.

## Labels
`P1`, `frontend`, `courses`, `content`

**Comment by alexeygrigorev** [comment]
## Software Engineer Report

### Files Created/Modified

Templates
- `templates/content/course_detail.html` — Tightened syllabus mobile padding (`px-3 py-2.5 sm:px-4 sm:py-3` for module summaries, `px-2 py-1.5 sm:px-3 sm:py-2.5` for unit rows). Added `min-h-[44px]` to module summary so mobile tap target survives the tighter padding. Module-row chip uses `h-7 w-7 sm:h-6 sm:w-6` for mobile thumb comfort. Lesson count is now suppressed entirely when `module_total == 0` (no more "0 lessons" rendering).
- `templates/content/reader/_bottom_nav.html` — Mobile mark-complete now renders as a stand-alone full-width row above the prev/next pair (`sm:hidden`). Desktop keeps the original inline placement (`hidden sm:block`). Both prev/next links picked up `min-h-[44px]`.
- `templates/content/reader/_completion_button.html` — Added optional `completion_button_full_width` and `completion_button_id_suffix` so the same partial can render the mobile + desktop variants without duplicate IDs. Added `min-h-[44px]` to both variants.
- `templates/content/reader/_sidebar.html` — Workshop tutorial sidebar rows now share the course sidebar's `px-2 py-1.5` row padding and use the same circle / check-circle-2 pair for completion state (parity).
- `templates/content/reader/_scripts.html` — Toggle handler now updates every sibling button that shares the same `data-completion-url`, so the mobile and desktop copies stay in sync.
- `templates/content/dashboard.html` — Suppressed zero-count rendering for poll vote / option counts ("0 votes", "0 options") in the dashboard sidebar.
- `templates/content/workshop_detail.html` — Reworded the tutorial card so it never renders "0 pages of step-by-step instructions".

Tests
- `content/tests/test_reader_mobile_483.py` — 14 new Django tests covering syllabus mobile spacing/tap target, zero-count suppression on the syllabus and dashboard, mobile/desktop bottom-nav split, completion-button min-height, prev/next min-height, anonymous gating, workshop ↔ course parity (sidebar row padding + circle glyph + bottom-nav split).
- `playwright_tests/test_reader_mobile_483.py` — 6 new Playwright scenarios at 390x844 and 1280x900: syllabus tap target on mobile, zero-lessons suppression on mobile, mobile completion row above prev/next + click toggles + reload persistence, long-title prev/next no horizontal overflow at 390px, workshop tutorial parity, and desktop regression guard.

### Tests
- New Django: 14/14 passing (`content.tests.test_reader_mobile_483`).
- All `content` Django tests: 2026/2026 passing (full suite, parallel).
- Playwright (issue #483 scenarios): 6/6 passing.
- Playwright (`test_workshop_completion.py`): 5/5 passing — confirms completion toggle still works post-refactor.
- Lint: `ruff check` clean for the new files (pre-existing errors in `payments/` are out of scope).

### What Works
- Course syllabus on mobile is visibly tighter (less wasted vertical space) but module rows still expose a 44px tap target.
- "0 lessons" / "0 votes" / "0 options" / "0 pages" copy is gone wherever it could surface.
- Mobile mark-complete sits as a full-width row directly under the body, above the prev/next pair. Click flips the state and the change persists across reload.
- Mobile and desktop completion buttons stay in sync after a click (shared completion-url query in JS).
- Workshop tutorial sidebar rows now match course unit sidebar rows visually (same padding tokens, same icon pair).
- Long prev/next titles still fit a 390px viewport without overflowing the body.

### Known Limitations
- The phrase from the source recording ("Catch announcement 0") could not be reproduced verbatim anywhere in the codebase; the closest matching artifacts were "0 lessons" on the course detail and "0 votes / 0 options" on the dashboard, both fixed. If a user reports a different exact location later we can widen the suppression.
- 4 unrelated Playwright tests in `test_workshop_tutorial_sidebar.py` and 10 in `test_course_units.py` are pre-existing failures (the `_create_course` helper passes `instructor_name`, which is no longer a Course field). These are not in scope for #483 — opening as a separate intake item is appropriate.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by alexeygrigorev** [comment]
## QA Screenshots (issue #483)

Captured against a freshly-seeded snapshot of the worktree at viewports 390x844 (mobile) and 1280x900 (desktop). Three of the pages render leaked Django `{# ... #}` comments as user-visible text — see images marked LEAKED below.

### /account/ (1280x900) — auth sanity

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/00_account_check.png)

### /courses/issue-483-course (390x844)

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/01_course_detail_mobile.png)

### /courses/issue-483-course (1280x900)

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/02_course_detail_desktop.png)

### /courses/.../setup (390x844) — LEAKED template comment above mark-complete

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/03_course_unit_mobile.png)

### /courses/.../setup (1280x900) — LEAKED template comment above mark-complete

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/04_course_unit_desktop.png)

### /workshops/.../tutorial/intro (390x844) — LEAKED template comment

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/05_workshop_tutorial_mobile.png)

### /workshops/.../tutorial/intro (1280x900) — LEAKED template comment

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/06_workshop_tutorial_desktop.png)

### / dashboard (390x844)

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/07_dashboard_mobile.png)

### / dashboard (1280x900)

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/08_dashboard_desktop.png)

### /workshops/issue-483-workshop (390x844) — LEAKED template comment in tutorial card

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/09_workshop_detail_mobile.png)

### /workshops/issue-483-workshop (1280x900) — LEAKED template comment in tutorial card

![](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/10_workshop_detail_desktop.png)

**Comment by alexeygrigorev** [comment]
## QA Review

### Verdict: FAIL — leaked Django template comments render as user-visible text on three pages.

### Test summary
| Suite | Result |
| --- | --- |
| Focused #483 Django tests (`content.tests.test_reader_mobile_483`) | 14 passed / 0 failed |
| Full Django suite (`make test`, parallel) | 6135 passed / 0 failed / 1 skipped (unrelated) |
| Coverage (`make coverage`) | 92% (>=85% gate) |
| Playwright (`make playwright`, full sweep) | Run was preempted twice by parallel worktree pytest holding port 8765; partial run showed pre-existing failures only in `playwright_tests/test_event_recordings.py` and `playwright_tests/test_events_calendar.py` snippets — none of those touch reader chrome. Focused #483 file (`playwright_tests/test_reader_mobile_483.py`) passed 6/6 in the SWE's prior run. |
| Ruff | Clean on the worktree's modified files. |

### Critical regression — Django `{# ... #}` comment leak (3 pages)

Django's `{# ... #}` comment syntax is single-line only; multi-line `{# ... #}` blocks are NOT stripped and render as raw text. This rule is well-documented in `_docs/testing-guidelines.md` and prior tester memory (`feedback_django_comment_leak.md`).

The fix introduces FOUR multi-line `{# ... #}` blocks; THREE of them leak to live HTML:

| File | Line | Symptom |
| --- | --- | --- |
| `templates/content/reader/_bottom_nav.html` | 15-18 | 4 lines of internal documentation render directly above the mark-complete button on every course-unit reader page and every workshop-tutorial reader page. |
| `templates/content/workshop_detail.html` | 122-125 | 4 lines render inside the "Follow the tutorial" card; ironically the leaked text contains the literal phrase `"0 pages"` — the exact artifact the new template change was meant to suppress. |
| `templates/content/reader/_sidebar.html` | 71-73 | 3 lines leak inside the workshop-tutorial sidebar (only visible when the sidebar opens; still in DOM and assistive tech reads it). |

The single-line `{# Desktop-only inline placement of the mark-complete button. #}` in `_bottom_nav.html` (line 34) does NOT leak; the `dashboard.html` 2-line block didn't trigger in my fixture (no rendered open polls) but is the same latent bug pattern and will leak as soon as `active_polls` has rows.

Reproduced live with the test client:

```
course-unit:        leaked-comments=['{# Mobile-only']
workshop-tutorial:  leaked-comments=['{# Issue #483', '{# Mobile-only']
workshop-detail:    leaked-comments=['{# Issue #483']
```

### How to fix
Replace every multi-line `{# ... #}` block with `{% comment %}...{% endcomment %}`:

```
{# convert these blocks #}
  ↓
{% comment %} ... {% endcomment %}
```

Files to update (all in the worktree's diff):
- `templates/content/reader/_bottom_nav.html` (the Mobile-only block at line 15)
- `templates/content/reader/_sidebar.html` (the workshop-sidebar block at line 71)
- `templates/content/workshop_detail.html` (the "0 pages" block at line 122)
- `templates/content/dashboard.html` (the 2-liner at line 414, latent but wrong by the same rule)

Also add a regression assertion to `content/tests/test_reader_mobile_483.py` so this pattern can't reappear silently. The existing tests use windowed substring searches that look NEAR the testid but never check for the literal `{# ` or `#}` strings in the response body. Suggested:

```python
self.assertNotIn('{# ', body, 'Multi-line Django {# ... #} comment leak')
self.assertNotIn(' #}', body)
```

The current test `test_mobile_completion_row_present_and_hidden_on_desktop` already pulls a 200-char window around the testid — the leaked comment was inside that window the whole time and went undetected.

### Other ACs verified

- AC1 (syllabus tighter, 44px tap target): PASS — `min-h-[44px]` retained, `px-3 py-2.5 sm:px-4 sm:py-3` applied; "Coming Soon (empty)" module renders with NO `0 lessons` text.
- AC2 (sidebar parity): partial PASS — workshop-tutorial sidebar uses the same `px-2 py-1.5` and the matching circle/check glyph as the course sidebar; FAILS only because the `{% comment %}` block leaks.
- AC5 (completion auto-enroll, completion service contract): PASS via 14/14 focused tests + the full content suite.
- AC6 (no overflow at 390px on long titles): PASS — `test_long_prevnext_titles_do_not_overflow_390px` and the runtime screenshot show truncation working.
- AC8 (completion API JSON contract): PASS — no API view changes; `test_workshop_completion.py` 5/5 (per SWE) and `content` suite still green.

### Pre-existing failures (NOT a #483 issue)
The SWE flagged `playwright_tests/test_course_units.py` and parts of `playwright_tests/test_workshop_tutorial_sidebar.py` as failing under intake #505 due to a stale `instructor_name` kwarg. The new `playwright_tests/test_reader_mobile_483.py` deliberately defines local fixtures to avoid that helper drift. I did not gate on those.

### Screenshots
See the previous comment for image evidence at 390x844 and 1280x900 viewports. The `03_*`, `04_*`, `05_*`, `06_*`, `09_*`, and `10_*` screenshots show the leaked comment text directly.

### Verdict: FAIL — please fix the four `{# ... %}` blocks (replace with `{% comment %}...{% endcomment %}`), add a test for `{# ` not appearing in the rendered body, and re-run.

**Comment by alexeygrigorev** [comment]
## Software Engineer Update — comment-leak fix

Tester correctly flagged that multi-line `{# ... #}` blocks leak the comment text as visible page content (Django `{# #}` is single-line only). Fixed by converting all four offending blocks to `{% comment %}...{% endcomment %}`.

### Files re-edited

- `templates/content/reader/_bottom_nav.html` (mobile-completion explainer, lines 15-18)
- `templates/content/workshop_detail.html` (the block that leaked the literal `"0 pages"`, lines 122-125)
- `templates/content/reader/_sidebar.html` (workshop sidebar parity note, lines 71-73)
- `templates/content/dashboard.html` (zero-count suppression note, lines 414-415)

### Diff audit

`git diff main -- '*.html' | grep -E '^\+\s*\{#'` returns no multi-line comment opens. The only remaining hit is `_bottom_nav.html` line 213, which is a single-line `{# ... #}` (open and close on the same physical line) and is safe.

### Regression test added

New `TestNoDjangoCommentLeak` class in `content/tests/test_reader_mobile_483.py` renders the dashboard, course detail, course unit reader, workshop detail, and workshop tutorial reader pages and asserts neither `'{# '` nor `' #}'` appears in any response body. This catches future leaks of the same class.

### Test counts

- Django: `uv run python manage.py test content.tests.test_reader_mobile_483` — 19 tests, all passing (was 14 before, +5 regression tests for the new class).
- Playwright: `uv run pytest playwright_tests/test_reader_mobile_483.py -v` — 6 tests, all passing.
- Lint: `uv run ruff check content/tests/test_reader_mobile_483.py` — clean.

### ACs

Re-flipped AC2, AC3, AC4, AC7 back to `[x]`. The full AC list is now all checked.

Not committed/pushed yet — awaiting tester re-run.

**Comment by alexeygrigorev** [comment]
## QA Review (re-run)

### Verdict: PASS

The previous comment-leak failure has been fixed and a regression test (`TestNoDjangoCommentLeak`) is in place. All ACs verified.

### Comment-leak verification

`git diff main -- '*.html' | grep -E '^\+\s*\{#'` returns only the single physical-line case in `_bottom_nav.html` line 213 (`{# Desktop-only inline placement of the mark-complete button. #}`), which is safe (open and close on the same line).

I rendered all four affected pages (dashboard, course unit reader, workshop detail, workshop tutorial reader) at 1280x900 and 390x844 against a real running Django server and grep'd the response HTML — clean across all 8 pages:

```
=== LEAK / ZERO-COUNT REPORT ===
CLEAN: no comment leaks or zero-count artifacts found in any of the 8 captures.
```

I also injected a multi-line `{# ... #}` leak into `_bottom_nav.html` and confirmed `TestNoDjangoCommentLeak.test_course_unit_reader_has_no_comment_leak` fails with the expected message, then restored. The regression guard is real.

### Acceptance Criteria

- [x] AC1 PASS: syllabus rows tighter on mobile, 44px tap target preserved
- [x] AC2 PASS: course unit and workshop tutorial sidebars share `px-2 py-1.5`, circle/check completion glyph, and chrome (visually identical in screenshots)
- [x] AC3 PASS: mark-complete is a stand-alone full-width row on mobile above prev/next (no longer stranded between them)
- [x] AC4 PASS: button labels, completed/loading/disabled states, min-h 44px on both viewports
- [x] AC5 PASS: completion auto-enroll and completion service contract preserved (no view changes; service tests still green)
- [x] AC6 PASS: long prev/next titles truncate without overflow at 390px (screenshot + `test_long_prevnext_titles_do_not_overflow_390px`)
- [x] AC7 PASS: zero-count artifacts gone — no `0 lessons`, `0 votes`, `0 options`, `0 pages`, `announcement 0` substrings in any rendered page
- [x] AC8 PASS: completion API JSON contract unchanged

### Commands and counts

| Command | Result |
| --- | --- |
| `make test` | 6140 passed, 1 skipped, 0 failed (149s) |
| `make coverage` | 92% TOTAL (>= 85% gate, exit 0) |
| `uv run python manage.py test content.tests.test_reader_mobile_483 -v 2` | 19/19 passed (14 prior + 5 new `TestNoDjangoCommentLeak`) |
| `uv run pytest playwright_tests/test_reader_mobile_483.py -v` | 6/6 passed (9.93s) |
| `make playwright` (full suite) | 527 passed, 1 skipped, 74 failed (812s) |

### Classification of `make playwright` failures

All 74 failures are pre-existing on this worktree's branch base, NOT caused by #483. Root cause is the `instructor_name` / `instructor_bio` schema drift in shared Playwright fixtures, which was fixed on `main` by PR #505 but does not exist on this worktree branch (it predates the merge). Unique error classes:

- `TypeError: Course() got unexpected keyword arguments: 'instructor_name'` — 47 occurrences
- `TypeError: Course() got unexpected keyword arguments: 'instructor_name', 'instructor_bio'` — present
- `TypeError: Workshop() got unexpected keyword arguments: 'instructor_name'` — 22 occurrences
- Downstream Playwright timeouts in tests whose fixture setup was killed by the above

The new `playwright_tests/test_reader_mobile_483.py` deliberately defines local `_create_course` / `_create_workshop` helpers that match the current schema, which is why its 6 tests pass independently. Once #483 is merged into main (which already contains #505), the next full Playwright run will be clean.

### Screenshots (1280x900 desktop, 390x844 mobile)

Course unit reader (mobile): mark-complete is a stand-alone full-width row above `Next: Unit Two`, no `{# ... #}` artifacts.
![mobile course unit reader](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-mobile_course_unit_reader.png)

Workshop tutorial reader (mobile): same layout as course unit, sidebar parity preserved.
![mobile workshop tutorial reader](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-mobile_workshop_tutorial_reader.png)

Workshop detail (mobile): tutorial card shows `2 pages of step-by-step instructions`, no `0 pages` artifact.
![mobile workshop detail](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-mobile_workshop_detail.png)

Dashboard (mobile): `No active polls right now` empty state, no `0 votes` / `announcement 0` artifacts.
![mobile dashboard](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-mobile_dashboard.png)

Desktop course unit reader: inline mark-complete preserved on left, sidebar uses circle/check glyph.
![desktop course unit reader](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-desktop_course_unit_reader.png)

Desktop workshop tutorial reader: visually identical chrome to course unit reader (parity goal met).
![desktop workshop tutorial reader](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-desktop_workshop_tutorial_reader.png)

Desktop dashboard:
![desktop dashboard](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-desktop_dashboard.png)

Desktop workshop detail:
![desktop workshop detail](https://raw.githubusercontent.com/AI-Shipping-Labs/website/screenshots/issue-483/qa-rerun-desktop_workshop_detail.png)

### Approval

All ACs pass; Django suite, Django coverage and focused Playwright suite all green. The full `make playwright` suite has 74 unrelated pre-existing fails (instructor schema drift, fixed on main by #505, not in this worktree's base). Software engineer is approved to commit and push.

**Comment by alexeygrigorev** [comment]
## Product Review

### Verdict: ACCEPT

### Screenshots reviewed
All 8 QA re-run screenshots (4 mobile + 4 desktop) at 390x844 and 1280x900. No error pages, no broken layouts, no `{# ... #}` artifacts visible anywhere, dark theme consistent.

### User flow
- Mobile course-unit reader and mobile workshop-tutorial reader are now visibly the same shape: breadcrumb -> top-right Next link -> title -> content -> divider -> full-width "Mark as completed" row -> lime "Next:" button -> back-to-parent link -> "Course Navigation" / "Workshop Navigation" disclosure. The earlier complaint about mark-complete feeling stranded between prev/next is gone — it now reads as a deliberate end-of-lesson action.
- Desktop preserves the inline mark-complete on the left and "Next:" on the right; the sidebar parity (circle/check glyph, density) holds between course and workshop readers.

### Copy and messaging
- Workshop detail "Follow the tutorial" card now reads `2 pages of step-by-step instructions you can work through at your own pace.` — natural sentence, no `0 pages` artifact.
- Dashboard empty states are all helpful with CTAs: `No active polls right now` + `View past polls`, `No new notifications`, `No content available yet` + `Browse Blog`, `No upcoming events` + `Browse Events`. No `... 0` artifacts anywhere.

### Empty states
Tutorial pages list, syllabus modules with no lessons ("Coming Soon (empty)"), and dashboard widgets all degrade gracefully. AC7 met visually.

### Tap targets
Mobile "Mark as completed" row and lime "Next:" button visibly clear ~44px on the screenshot at 390x844. Syllabus rows preserved at min-h-[44px] per the diff and tester check.

### Consistency
Course-unit and workshop-tutorial readers are now visually interchangeable — same chrome, same buttons, same sidebar density. This was the explicit AC2 goal.

### Non-blocking notes (for future polish, not this issue)
- On the desktop course sidebar the active unit row reads slightly dimmer than the workshop sidebar's active row. Both are legible; possible follow-up if anyone else notices.
- The mobile bottom-nav still shows two collapsed disclosures (`Course Navigation` / `Workshop Navigation`) without the back-to-parent link being styled as a button — fine as-is, but a future iteration could group them.

### Next step
Software engineer is approved to commit the worktree changes on `worktree-agent-a955842afe78cf97f` with `Closes #483` in the message and push. Do not amend; create a fresh commit. The 74 pre-existing `make playwright` failures are out of scope (instructor schema drift fixed on main by #505) and will resolve once this branch is merged onto current main.
