### ISSUE TITLE
[cleanup] Remove EventSeries.cadence_weeks reserved field (unbuilt every-N-weeks stretch goal)

### ISSUE THREAD

**Issue by alexeygrigorev** [AI-Shipping-Labs/website#914]
From the simplification audit. EventSeries.cadence_weeks is stored + validated (api/views/event_series.py) + asserted in ~10 tests but drives NO scheduling (occurrences are bulk-created from an explicit payload; v1 always stores 1). Owner authorized cutting the stretch goal. Remove the field + a removal migration + its API validation + the test references. DEPENDS ON #854 (both touch event_series schedule/API) — implement AFTER #854 merges to avoid conflict. Requested by Alexey.

**Comment by alexeygrigorev** [comment]
## Screenshots

- `/studio/event-series` (desktop 1280x720, logged in as main@test.com): https://d31nukezbn4e3o.cloudfront.net/2026/06/11/2f41c417bd8741259826369defe67160-c86a3e4f6a319993.png
- `/studio/event-series/new` (desktop 1280x720, logged in as main@test.com): https://d31nukezbn4e3o.cloudfront.net/2026/06/11/f346a3dc6bf2441db5e9501f0b22ec5c-f6bcddc97bc3809d.png
- `/studio/event-series/1` (desktop 1280x720, logged in as main@test.com): https://d31nukezbn4e3o.cloudfront.net/2026/06/11/2bdbaf3952374eb78fd464da84ee7372-9dd75cbbc5f1268f.png

**Comment by alexeygrigorev** [comment]
## QA Review

Verified from scratch (the implementing SWE did not report test results).

### Test Summary
- `make test-core` (Django unit/integration): 1438 passed / 0 failed
- Targeted event-series + sprint-event-series suites: 168 passed / 0 failed
- Playwright E2E (core subset): 250 passed / 0 failed (1088 deselected)
- `manage.py check`: clean (0 issues)
- `makemigrations --check --dry-run`: No changes detected (migration 0025 covers the removal)
- `generate_openapi --check`: passes (see issue found below)

### Acceptance Criteria
- [x] PASS: `cadence_weeks` removed from `events/models/event_series.py`
- [x] PASS: Removal migration `0025_remove_eventseries_cadence_weeks.py` drops exactly that one field, depends on 0024, applies cleanly
- [x] PASS: API validation + serialization removed from `api/views/event_series.py` (writable fields, serializer, validator, request schema, example)
- [x] PASS: Studio create view no longer sets `cadence_weeks` (`studio/views/event_series.py`)
- [x] PASS: ~10 test files updated — only the `cadence_weeks` fixture kwargs and the field-list/validation assertions were removed; no whole meaningful tests deleted
- [x] PASS: `grep -rn cadence_weeks` (excluding `.claude/worktrees` and migrations) returns nothing — fully removed from code and tests
- [x] PASS: `cadence` label field is UNTOUCHED (model field, serializer, validation, Studio list display all intact); runtime confirms `hasattr(EventSeries(), 'cadence_weeks')` is False
- [x] PASS: Event-series create/edit + add-occurrence flows render and work without the field (no missing-attribute errors) — verified via screenshots of list, new, and detail pages

### Issue Found and Fixed
- The committed `_docs/openapi.json` is drift-checked in CI (`make check-openapi-drift`). The SWE removed `cadence_weeks` from the API views but did NOT regenerate the spec, so `generate_openapi --check` failed (exit 1). Regenerated the spec; the only delta is the 12 `cadence_weeks` lines, and the drift check now passes (exit 0). This regenerated file is part of the uncommitted change set and must be committed with the rest.

### Verdict: PASS (with the openapi.json regeneration included)

**Comment by alexeygrigorev** [comment]
## Software Engineer Report

Built on latest main (includes #854 event-series schedule work; nothing reverted). Confirmed up front via `grep -rn cadence_weeks` that the field drove NO scheduling: it was only stored, validated in `api/views/event_series.py`, defaulted to 1 on create in both the API and Studio views, and asserted in test fixtures. Occurrences are bulk-created from explicit payloads, so removal is behavior-preserving.

### Files Modified
- `events/models/event_series.py` — removed the `cadence_weeks` PositiveIntegerField. Did NOT touch the `cadence` weekly-label field.
- `events/migrations/0025_remove_eventseries_cadence_weeks.py` — new migration, single `RemoveField` op (verified it drops only that field).
- `api/views/event_series.py` — removed the field from the example object, `SERIES_WRITABLE_FIELDS`, `serialize_event_series`, the `_collect_series_values` validation block, the `EventSeries(...)` create default, and both OpenAPI request-body schemas.
- `studio/views/event_series.py` — removed the `cadence_weeks=1` create kwarg.
- `_docs/openapi.json` — regenerated (12 lines removed); `generate_openapi --check` is clean.
- Test references removed (assertions/fixtures only, surrounding tests intact): `api/tests/test_event_series.py` (keyset assertion, body assertion, validation-error payload+loop, 3 fixtures), `integrations/tests/test_banner_generator_dispatch.py`, `plans/tests/test_sprint_event_series.py`, `studio/tests/test_sprint_event_series.py`, `studio/tests/test_studio_datetime_picker_tz.py` (x2), `studio/tests/test_studio_datetime_picker_tz_default_855.py`, `studio/tests/test_event_series_regenerate_banner.py`, `playwright_tests/test_sprint_event_series_565.py`, `playwright_tests/test_studio_event_tz_browser_default_855.py`, `playwright_tests/test_studio_event_series_banner_896.py`.

### Grep Evidence (after)
`grep -rn cadence_weeks --include=*.py` (excluding `.claude/worktrees`) returns only the two historical migration files: `0014_event_groups_and_origin.py` (which created the field) and `0025_remove_eventseries_cadence_weeks.py` (which removes it). No source, view, serializer, or test references remain. The live model has no such field. `cadence` (weekly label) untouched.

### Migration
`events/migrations/0025_remove_eventseries_cadence_weeks.py` — applied cleanly. `makemigrations --check --dry-run events` reports "No changes detected".

### Test Results
- `make test-core`: Ran 1438 tests, OK (0 failures).
- `make test-playwright-core` (no PLAYWRIGHT_DJANGO_PORT set): 250 passed, 1088 deselected, 0 failures (8:00).
- Full Django suite (`manage.py test`): Ran 5414 tests. The openapi-check test passes after the spec regeneration. Two failures remain and are PRE-EXISTING / unrelated to this issue — both concern `ses.CAMPAIGN_BATCH_INTERVAL_SECONDS` introduced by #922 (`integrations.tests.test_settings.test_every_registered_key_has_docs_url` — missing `docs_url`; `api.tests.test_integration_settings.test_get_response_does_not_contain_value_substring`). My commit touches none of `settings_registry.py`, `test_settings.py`, or `test_integration_settings.py`.
- `ruff check .`: clean.

### Deviations / Notes
- Two pre-existing full-suite failures from #922 (`ses.CAMPAIGN_BATCH_INTERVAL_SECONDS` docs_url + settings-value leak) are present on the base branch and should be tracked separately — not caused by this change.
- In `api/tests/test_event_series.py::test_create_series_validation_errors`, I removed the `cadence_weeks: 0` payload entry and its assertion (the field no longer validates); the remaining `name`/`day_of_week`/`start_time`/`cadence` error assertions are intact, so the test still verifies validation.
